### ISSUE TITLE
🐛 [Bug]: 文档主题错误

### ISSUE THREAD

**Issue by GaoNeng-wWw** [DevCloudFE/vue-devui#1004]
### Version

latest

### Vue Version

/

### Link to minimal reproduction

https://vue-devui.github.io/

### Step to reproduce

1. 打开[文档](https://vue-devui.github.io/)
2. 切换主题至追光
3. 错误复现如下图

![1](https://user-images.githubusercontent.com/31283122/177755465-1d15e71e-8597-420b-b5ed-b5e2ca859e9d.PNG)
![2](https://user-images.githubusercontent.com/31283122/177755456-f6c6241e-3cb4-40c8-82d1-1cd08f7d5b6f.PNG)
![3](https://user-images.githubusercontent.com/31283122/177755449-bf9df53f-0e51-4e43-a2ce-0a112444ba4f.PNG)

### What is expected

超链接文本应当为蓝色、白色或其他颜色

白色面板应当为黑色、深色或其他颜色

### What is actually happening

也许是```--c-text``` 变量颜色有错

**Comment by kagol** [comment]
是的，没用主题变量的原因

**Comment by kagol** [comment]
已解决并部署
@GaoNeng-wWw
