### ISSUE TITLE
🐛 [Bug]: button按钮在 “追光” 主题下 带icon按钮 icon颜色显示异常 

### ISSUE THREAD

**Issue by vaebe** [DevCloudFE/vue-devui#1013]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/button/#%E5%8A%A0%E8%BD%BD%E4%B8%AD%E7%8A%B6%E6%80%81
官网可直接复现

### Step to reproduce

1. 打开官网地址 https://vue-devui.github.io/components/button/#%E5%8A%A0%E8%BD%BD%E4%B8%AD%E7%8A%B6%E6%80%81
2. 切换主题为 追光
3. 查看 “图标按钮” 

### What is expected

图标按钮 追光主题下 icon 显示正常

### What is actually happening

图标按钮 追光主题下 icon 未显示 或显示异常

**Comment by vaebe** [comment]
<img width="939" alt="截屏2022-07-10 下午5 41 00" src="https://user-images.githubusercontent.com/52314078/178140089-e6113a3b-0ce2-4898-92a8-07c784e52bf0.png">

**Comment by kagol** [comment]
Fixed by @Lonely-shang on #1427
