### ISSUE TITLE
🐛 [Bug]: tabs tab样式显示异常

### ISSUE THREAD

**Issue by vaebe** [DevCloudFE/vue-devui#1014]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

复现地址
https://vue-devui.github.io/components/tabs/#pills-%E7%B1%BB%E5%9E%8B

### Step to reproduce

1. 打开 https://vue-devui.github.io/components/tabs/#pills-%E7%B1%BB%E5%9E%8B
2. 选择 “追光” 主题
3. 查看  Options 类型 下tabs

### What is expected

tabs tab 样式显示正常

### What is actually happening

tabs tab样式显示异常

### Any additional comments (optional)

<img width="920" alt="截屏2022-07-10 下午5 55 13" src="https://user-images.githubusercontent.com/52314078/178139988-35766d61-4f6f-4b4f-ab48-f363b1d4b4d1.png">

**Comment by Whbbit1999** [comment]
tab-nav.scss文件颜色变量写错了
