### ISSUE TITLE
🐛 [Bug]: checkbox 复选框 “追光” 主题 样式异常

### ISSUE THREAD

**Issue by vaebe** [DevCloudFE/vue-devui#1015]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

复现地址
https://vue-devui.github.io/components/checkbox/#%E5%B0%BA%E5%AF%B8%E5%92%8C%E8%BE%B9%E6%A1%86

### Step to reproduce

1. 打开 https://vue-devui.github.io/components/checkbox/#%E5%B0%BA%E5%AF%B8%E5%92%8C%E8%BE%B9%E6%A1%86
2. 选择 “追光” 主题
3. 选择查看。按钮形态 部分

### What is expected

checkbox 复选框 边框样式显示正常

### What is actually happening

checkbox 复选框 边框样式显示异常

### Any additional comments (optional)

<img width="872" alt="截屏2022-07-10 下午6 02 48" src="https://user-images.githubusercontent.com/52314078/178140482-fe174b8c-a747-4ebf-ab2f-78f5eff59615.png">

**Comment by kagol** [comment]
看着应该是没用主题变量或者是主题变量用得不对导致的
