### ISSUE TITLE
🐛 [Bug]: Tabs溢出不截断

### ISSUE THREAD

**Issue by GaoNeng-wWw** [DevCloudFE/vue-devui#1062]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/tabs/#%E6%B7%BB%E5%8A%A0-%E5%88%A0%E9%99%A4

### Step to reproduce

1. 打开官网
2. 打开Tabs组件
3. 在添加/删除节不断添加
4. 会发现溢出不截断错误

### What is expected

超出容器宽度时应当截断或显示省略号，例如[React Tabs](https://react-devui.com/components/Tabs#TabsLotsDemo)

### What is actually happening

没有添加overflow hidden或其他相应样式

**Comment by kagol** [comment]
确实有问题

**Comment by xzxldl55** [comment]
@kagol 感觉应该改造成这个样子，滚动显示剩下的，怎么样
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/22699218/179693902-d2113c3d-7a74-4da8-9857-c6ade6b9ba95.png">

**Comment by GaoNeng-wWw** [comment]
> @kagol 如果改成超出滚动的话会不会效果更好✌️ <img alt="image" width="1333" src="https://user-images.githubusercontent.com/22699218/179693902-d2113c3d-7a74-4da8-9857-c6ade6b9ba95.png">

滑块和轨道或许最好小一些，因为Tab通常用于顶部，如果轨道太粗就容易显得有些头重脚轻😉

**Comment by linxiang07** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/40119767/181403024-e67deb8c-261e-45b2-847d-523cbed90290.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/40119767/181403252-81666a1a-2567-433a-bf25-996cfa03d6d4.png">
可以参考antv、element-plus的做法

**Comment by kagol** [comment]
Fixed by @handsomezyw on #1301

**Comment by kagol** [comment]
> <img alt="image" width="602" src="https://user-images.githubusercontent.com/40119767/181403024-e67deb8c-261e-45b2-847d-523cbed90290.png">
> 
> <img alt="image" width="771" src="https://user-images.githubusercontent.com/40119767/181403252-81666a1a-2567-433a-bf25-996cfa03d6d4.png">
> 
> 可以参考antv、element-plus的做法

先确保不会溢出，后续可以优化成可以前进后退这种交互形态
