### ISSUE TITLE
🐛 [Bug]: Cascader组件清除按钮歪斜

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1159]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

<img width="613" alt="image" src="https://user-images.githubusercontent.com/40119767/182418777-a29247d5-4bd2-42c8-b724-1f9ca24147e2.png">

### Step to reproduce

打开Cascader组件

### What is expected

语气清除按钮等按钮位置正确

### What is actually happening

打开Cascader组件歪斜

**Comment by kagol** [comment]
Fixed by @Zz-ZzzZ on #1413
