### ISSUE TITLE
🐛 [Bug]: menu元素被选中，收起后会被取消选择

### ISSUE THREAD

**Issue by GaoNeng-wWw** [DevCloudFE/vue-devui#1163]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/menu/#%E6%94%B6%E7%BC%A9%E8%8F%9C%E5%8D%95

### Step to reproduce

/

### What is expected

收起与展开应当一致样式

### What is actually happening

收起后，被选择样式被清除

**Comment by kagol** [comment]
@GaoNeng-wWw 没看懂什么意思，可否贴个图？

**Comment by GaoNeng-wWw** [comment]
> @GaoNeng-wWw 没看懂什么意思，可否贴个图？
![](https://user-images.githubusercontent.com/31283122/183417181-5010a7b3-90ff-4246-8620-aea140a9b72f.gif)

我想应该是状态没有修改的原因，或许加个store可以解决？

**Comment by kagol** [comment]
Fixed by @GaoNeng-wWw on #1200
