### ISSUE TITLE
🐛 [Bug]: Switch demo歪斜、没有间距

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1168]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

<img width="559" alt="image" src="https://user-images.githubusercontent.com/40119767/182646238-c441ada2-8861-467a-a971-98026cc43f11.png">

### Step to reproduce

打开switch页面

### What is expected

整齐、不歪斜

### What is actually happening

不整齐、歪斜

**Comment by kagol** [comment]
这里涉及两个问题：
1. switch没有对齐的问题，这个可以在组件内部解决
2. switch之间没有间隔，这个应该在demo文档里解决

**Comment by kagol** [comment]
Fixed by @flingyp on #1171
