### ISSUE TITLE
🐛 [Bug]: button按钮设置颜色以及形态未正确展示

### ISSUE THREAD

**Issue by dbsdaicheng** [DevCloudFE/vue-devui#1169]
### Version

"vue-devui": "^1.0.0-beta.220801"

### Vue Version

"vue": "^3.2.37"

### Link to minimal reproduction

![image](https://user-images.githubusercontent.com/62135142/182750655-cdf98151-d1e2-45c9-b31d-52e779b23bb7.png)

### Step to reproduce

<d-button variant="solid" color="secondary">按钮</d-button>

### What is expected

没有展示对应的solid的按钮，而是outline的按钮

### What is actually happening

没有展示对应的solid的按钮，而是outline的按钮

**Comment by flingyp** [comment]
能贴出你使用Button组件的相关代码吗？

**Comment by dbsdaicheng** [comment]
> 能贴出你使用Button组件的相关代码吗？

<d-button variant="solid" color="secondary">Outline ButtonOutline</d-button>

**Comment by dbsdaicheng** [comment]
<d-button variant="solid" color="secondary">Outline ButtonOutline</d-button>

**Comment by dbsdaicheng** [comment]
“<d-button variant="solid" color="secondary">Outline ButtonOutline</d-button>”

**Comment by dbsdaicheng** [comment]
`<d-button variant="solid" color="secondary">Outline ButtonOutline</d-button>`

**Comment by dbsdaicheng** [comment]
> 能贴出你使用Button组件的相关代码吗？

`<d-button variant="solid" color="secondary">Outline ButtonOutline</d-button>`

**Comment by GaoNeng-wWw** [comment]
请问可以给出一个最小复现仓库吗？

**Comment by dbsdaicheng** [comment]
> 请问可以给出一个最小复现仓库吗？

我是本地的一个项目，通过npm安装devUI。没有上传到github仓库

**Comment by kagol** [comment]
该问题是未初始化主题导致的，按照以下步骤操作即可解决：
- 安装devui-theme主题库：`npm i devui-theme`
- 初始化主题为无限主题

在项目的`main.ts`文件中增加以下内容：
```
import { ThemeServiceInit, infinityTheme } from 'devui-theme';

ThemeServiceInit({ infinityTheme }, 'infinityTheme');
```

**Comment by kagol** [comment]
Fixed by @kagol on #1174

**Comment by kagol** [comment]
@all-contributors please add @dbsdaicheng for test
