### ISSUE TITLE
🐛 [Bug]: button设置颜色primary，形态text时样式不正确，hover时文字有下划线

### ISSUE THREAD

**Issue by dbsdaicheng** [DevCloudFE/vue-devui#1170]
### Version

"vue-devui": "^1.0.0-beta.220801"

### Vue Version

"vue": "^3.2.37"

### Link to minimal reproduction

![image](https://user-images.githubusercontent.com/62135142/182752955-cb71dcd4-09b5-4f66-8fa8-77cdfc4ecde5.png)

### Step to reproduce

<d-button variant="text" color="primary">Outline ButtonOutline</d-button>

### What is expected

button设置颜色primary，形态text时样式不正确，hover是文字有下划线

### What is actually happening

button设置颜色primary，形态text时样式不正确，hover是文字有下划线

**Comment by kagol** [comment]
Fixed by @kagol on #1192
