### ISSUE TITLE
🐛 [Bug]: tree 删除节点api处理错误

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1179]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

<img width="743" alt="image" src="https://user-images.githubusercontent.com/40119767/183101056-2a70231d-8980-41a4-ad42-adee12b7083d.png">

### Step to reproduce

增加节点之后删除

### What is expected

删除所有子节点之后能增加`isLeaf=true`

### What is actually happening

删除所有子节点之后不增加`isLeaf=true`

**Comment by kagol** [comment]
Let me solve this problem.

**Comment by kagol** [comment]
Fixed by @kagol on #1195
