### ISSUE TITLE
🐛 [Bug]: Button 设计了四种类型的尺寸，可是实际上只有两种

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1183]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

<img width="666" alt="image" src="https://user-images.githubusercontent.com/40119767/183252521-38375847-8b09-4915-baa4-c9edade0653b.png">

[example](https://devcloudfe.github.io/devui-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwic3BhY2VcIj5cbiAgICAgIDxkLWJ1dHRvbiBzaXplPVwieHNcIj5NaW5pPC9kLWJ1dHRvbj5cbiAgICAgIDxkLWJ1dHRvbiBzaXplPVwic21cIj5TbWFsbDwvZC1idXR0b24+XG4gICAgICA8ZC1idXR0b24+TWVkaXVtPC9kLWJ1dHRvbj5cbiAgICAgIDxkLWJ1dHRvbiBzaXplPVwibGdcIj5MYXJnZTwvZC1idXR0b24+ICBcbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgc2V0dXBEZXZ1aSB9IGZyb20gJy4vZGV2dWkuanMnXG5cbi8vIGRvbid0IHJlbW92ZVxuc2V0dXBEZXZ1aSgpXG48L3NjcmlwdD5cbjxzdHlsZT5cbiAgLnNwYWNlIC5kZXZ1aS1idXR0b246Zmlyc3QtY2hpbGQge1xuICAgIG1hcmdpbi1sZWZ0OiA4cHg7XG4gICAgbWFyZ2luLXRvcDogOHB4O1xuICAgIG1hcmdpbi1ib3R0b206IDhweDtcbiAgfVxuICAuc3BhY2UgLmRldnVpLWJ1dHRvbiB7XG4gICAgbWFyZ2luLXJpZ2h0OiA4cHg7XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOntcInZ1ZS1kZXZ1aVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vdnVlLWRldnVpQGxhdGVzdC92dWUtZGV2dWkuZXMuanNcIixcInZ1ZVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vdnVlQGxhdGVzdC9kaXN0L3Z1ZS5lc20tYnJvd3Nlci5qc1wiLFwidnVlLXJvdXRlclwiOlwiaHR0cHM6Ly91bnBrZy5jb20vdnVlLXJvdXRlckBsYXRlc3QvZGlzdC92dWUtcm91dGVyLmVzbS1icm93c2VyLmpzXCIsXCJAZmxvYXRpbmctdWkvZG9tXCI6XCJodHRwczovL3VucGtnLmNvbS9AZmxvYXRpbmctdWkvZG9tQGxhdGVzdC9kaXN0L2Zsb2F0aW5nLXVpLmRvbS5lc20uanNcIixcIkBmbG9hdGluZy11aS9jb3JlXCI6XCJodHRwczovL3VucGtnLmNvbS9AZmxvYXRpbmctdWkvY29yZUBsYXRlc3QvZGlzdC9mbG9hdGluZy11aS5jb3JlLmVzbS5qc1wiLFwiQHZ1ZXVzZS9jb3JlXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL2NvcmVAbGF0ZXN0L2luZGV4Lm1qc1wiLFwiQHZ1ZS9kZXZ0b29scy1hcGlcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvZGV2dG9vbHMtYXBpQGxhdGVzdC9saWIvZXNtL2luZGV4LmpzXCIsXCJAdnVldXNlL3NoYXJlZFwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZXVzZS9zaGFyZWRAbGF0ZXN0L2luZGV4Lm1qc1wiLFwidnVlLWRlbWlcIjpcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pQGxhdGVzdC9saWIvaW5kZXgubWpzXCJ9fSJ9)

### Step to reproduce

设置四种尺寸`xs`、`sm`、`md`、`lg`

### What is expected

应该有四种尺寸

### What is actually happening

只有两种尺寸

**Comment by kagol** [comment]
Fixed by @flingyp on #1185
