### ISSUE TITLE
✨ [Feature]: 使用 better-scripts 进行脚本命令的管理

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#1186]
### What problem does this feature solve

better-scripts 是一个更友好的管理脚本命令的工具，希望能够集成进来，参考文档：
[https://www.npmjs.com/package/better-scripts](https://www.npmjs.com/package/better-scripts)

### What does the proposed API look like

参考文档：
[https://www.npmjs.com/package/better-scripts](https://www.npmjs.com/package/better-scripts)

**Comment by iamyoki** [comment]
@kagol Assign me please~
