### ISSUE TITLE
🐛 [Bug]: Icon cannot be used

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1189]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

<img width="688" alt="image" src="https://user-images.githubusercontent.com/40119767/183299522-0231a402-0b19-4eb3-beb3-953ab65b1a3b.png">

[playground link](https://devcloudfe.github.io/devui-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiaWNvbi1leGFtcGxlXCI+XG4gICAgPGQtaWNvbiBuYW1lPVwiYWRkXCIgZGF0YS1pY29uPjwvZC1pY29uPlxuICA8L2Rpdj5cbiAgXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgc2V0dXBEZXZ1aSB9IGZyb20gJy4vZGV2dWkuanMnXG5cbi8vIGRvbid0IHJlbW92ZVxuc2V0dXBEZXZ1aSgpXG48L3NjcmlwdD5cbjxzdHlsZT5cbiAgLmljb24tZXhhbXBsZSB7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogcGlua1xuICB9XG4gIFtkYXRhLWljb25de1xuICAgIGJvcmRlcjogMnB4IHNvbGlkIHJlZDtcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e1widnVlLWRldnVpXCI6XCJodHRwczovL3VucGtnLmNvbS92dWUtZGV2dWlAbGF0ZXN0L3Z1ZS1kZXZ1aS5lcy5qc1wiLFwidnVlXCI6XCJodHRwczovL3VucGtnLmNvbS92dWVAbGF0ZXN0L2Rpc3QvdnVlLmVzbS1icm93c2VyLmpzXCIsXCJ2dWUtcm91dGVyXCI6XCJodHRwczovL3VucGtnLmNvbS92dWUtcm91dGVyQGxhdGVzdC9kaXN0L3Z1ZS1yb3V0ZXIuZXNtLWJyb3dzZXIuanNcIixcIkBmbG9hdGluZy11aS9kb21cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BmbG9hdGluZy11aS9kb21AbGF0ZXN0L2Rpc3QvZmxvYXRpbmctdWkuZG9tLmVzbS5qc1wiLFwiQGZsb2F0aW5nLXVpL2NvcmVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0BmbG9hdGluZy11aS9jb3JlQGxhdGVzdC9kaXN0L2Zsb2F0aW5nLXVpLmNvcmUuZXNtLmpzXCIsXCJAdnVldXNlL2NvcmVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2UvY29yZUBsYXRlc3QvaW5kZXgubWpzXCIsXCJAdnVlL2RldnRvb2xzLWFwaVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9kZXZ0b29scy1hcGlAbGF0ZXN0L2xpYi9lc20vaW5kZXguanNcIixcIkB2dWV1c2Uvc2hhcmVkXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL3NoYXJlZEBsYXRlc3QvaW5kZXgubWpzXCIsXCJ2dWUtZGVtaVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vdnVlLWRlbWlAbGF0ZXN0L2xpYi9pbmRleC5tanNcIn19In0=)

### Step to reproduce

Download the latest version and run

### What is expected

Icon can be used

### What is actually happening

Icon cannot be used

**Comment by linxiang07** [comment]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/40119767/183320602-140890c5-0295-4af9-8e90-97bdd472a2a8.png">
hen很奇怪，为什么我拉了最新的代码，在本地出现了这个问题

**Comment by kagol** [comment]
> <img alt="image" width="1061" src="https://user-images.githubusercontent.com/40119767/183320602-140890c5-0295-4af9-8e90-97bdd472a2a8.png">
> 
> 很奇怪，为什么我拉了最新的代码，在本地出现了这个问题

本地近期确实出现了这个问题

**Comment by kagol** [comment]
Let me solve this problem.

**Comment by kagol** [comment]
Fixed by @vaebe on #1230
