### ISSUE TITLE
🐛 [Bug]: Pagination 组件相同尺寸下 Select 和 Input 大小差距过大

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1228]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

<img width="888" alt="image" src="https://user-images.githubusercontent.com/40119767/184385743-42270a87-d25f-4c98-aa6d-d028cd502b16.png">

### Step to reproduce

[open](https://vue-devui.github.io/components/pagination/#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95)

### What is expected

建议Select选择和Input统一大小

### What is actually happening

大小不一

**Comment by linxiang07** [comment]
antd
<img width="573" alt="image" src="https://user-images.githubusercontent.com/40119767/184387017-b11fccf2-cd72-4a65-80fd-62bdae39fb43.png">
element-plus
<img width="577" alt="image" src="https://user-images.githubusercontent.com/40119767/184391383-c1ff4e17-299b-43eb-bda1-68ff0efd7658.png">

**Comment by linxiang07** [comment]
一开始我觉得 这个问题可能是 #1199 导致的，可是代码层面size并没有传递给 select 组件
<img width="602" alt="image" src="https://user-images.githubusercontent.com/40119767/184400134-e7dd1ffc-81cc-446c-8546-49657ded9ccf.png">

**Comment by kagol** [comment]
Fixed by @linxiang07 on #1264
