### ISSUE TITLE
🐛 [Bug]: 文档系统出现问题

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1236]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

未展开

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/40119767/184536564-cb893bf4-f505-499f-a43c-3eb010fc6974.png">

展开

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/40119767/184536609-17ca471c-65d9-4521-8a19-faa771cce81a.png">

### Step to reproduce

打开手风琴页面

### What is expected

显示正常

### What is actually happening

显示异常

**Comment by Whbbit1999** [comment]
kagol老师，这个问题没人认领吗？

**Comment by Whbbit1999** [comment]
这个问题已经解决了，等kagol老师合并就好

**Comment by Whbbit1999** [comment]
@kagol

**Comment by Whbbit1999** [comment]
@all-contributors  please add @Whbbit1999  for code.

**Comment by Whbbit1999** [comment]
@all-contributors please add @Whbbit1999  for code
