### ISSUE TITLE
🐛 [Bug]: time-select的step属性小于等于0时会卡死

### ISSUE THREAD

**Issue by qinwencheng** [DevCloudFE/vue-devui#1290]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

查看[这里](https://stackblitz.com/edit/vitejs-vite-xacsie/?file=src%2FApp.vue)

### Step to reproduce

查看[这里](https://stackblitz.com/edit/vitejs-vite-xacsie/?file=src%2FApp.vue)

### What is expected

期望输入不合法的step时能自动修正

**Comment by kagol** [comment]
Fixed by @qinwencheng on #1296
