### ISSUE TITLE
🐛 [Bug]: Mention 提及组件，第一次选择后删除输入，第二次输入点击无法选中

### ISSUE THREAD

**Issue by YUJIELL** [DevCloudFE/vue-devui#1292]
### Version

Vue DevUI 1.0

### Vue Version

^3.0.0

### Link to minimal reproduction

https://github.com/DevCloudFE/vue-devui/tree/dev/packages/devui-vue/devui/mention

### Step to reproduce

![动画](https://user-images.githubusercontent.com/32193756/188056347-1e78f5c7-3156-4e0f-aa1b-deef0863bf17.gif)

**Comment by kagol** [comment]
Fixed by @LiuSuY on #1305
