### ISSUE TITLE
🐛 [Bug]: Input 组件 clearable 属性出现问题

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#1329]
### Version

dev分支

### Vue Version

3.2.29

### Link to minimal reproduction

```vue
<template>
  <div class="devui-input-demo">
    <d-input v-model="valueClear" clearable @clear="handleClear" placeholder="请输入"></d-input>
  </div>
</template>

<script>
import { defineComponent, ref } from 'vue';

export default defineComponent({
  setup() {
    const handleClear = () => {
      console.log('clear');
    };
    const valueClear = ref(null);
    return {
      valueClear,
      handleClear,
    };
  },
});
</script>
```

### Step to reproduce

将当前代码应用到dev分支

### What is expected

正常使用

### What is actually happening

程序出现了问题

### Any additional comments (optional)

<img width="807" alt="image" src="https://user-images.githubusercontent.com/40119767/189145544-4a581aed-5e38-416b-a7c8-02039e1bc714.png">
如果`v-model`绑定的初始值为`null`这类没有`length`属性的类型，程序就会出现异常

**Comment by vaebe** [comment]
看来需要把 判断优化下🤪  等测试报错解决了 修一下
