### ISSUE TITLE
🐛 [Bug]: Cascader组件hover mode下样式异常

### ISSUE THREAD

**Issue by Zz-ZzzZ** [DevCloudFE/vue-devui#1355]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

none

### Step to reproduce

打开文档进入cascader组件下点击hover mode

### What is expected

点击时icon不会错位

### What is actually happening

![gp47f-u8xxv](https://user-images.githubusercontent.com/48228016/191637424-aa452271-f0a7-4ecf-afc5-54474a58f53f.gif)

**Comment by Cv-Engineer123** [comment]
#1413

**Comment by kagol** [comment]
Fixed by @Zz-ZzzZ on #1413
