### ISSUE TITLE
🐛 [Bug]: Modal拖拽异常

### ISSUE THREAD

**Issue by Cv-Engineer123** [DevCloudFE/vue-devui#1356]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/modal/

### Step to reproduce

打开modal并拖拽

### What is expected

正常拖拽

### What is actually happening

第一次拖拽时发生了不正确的偏移，请看下图

![20220923_153538](https://user-images.githubusercontent.com/48228016/191912914-19f7397d-4586-49d1-8e17-3b5e8e3b4af1.gif)

**Comment by Cv-Engineer123** [comment]
看了一下代码，是使用top/left transform来做的居中，由于初始设置了transform: translate(-50%, -50%)，而开始拖拽那一刻开始重新设置了translate覆盖了原本的定位数值，导致了位置偏移异常

**Comment by kagol** [comment]
Fixed by @wowCheng on #1364
