### ISSUE TITLE
✨ [Feature]: 建议改进button的加载中状态动画

### ISSUE THREAD

**Issue by buaalkn** [DevCloudFE/vue-devui#1417]
### What problem does this feature solve

如果在button中设置点击进入加载状态的话，动画内容会遮盖button原有内容，个人感觉不够美观
![image](https://user-images.githubusercontent.com/89232641/197711645-a40f30d9-9cdc-4c55-a522-563c719eefe3.png)

### What does the proposed API look like

感觉如果能类似naive ui的button，能够在点击后伸缩按钮长度，并加入加载动画更好
![image](https://user-images.githubusercontent.com/89232641/197711918-ec85a727-f456-4098-89cd-7c2d7854c100.png)
![image](https://user-images.githubusercontent.com/89232641/197712122-cab5c8bb-6fe7-4098-97a0-6f3860bd0db2.png)

**Comment by hqchqc** [comment]
感觉伸缩按钮长度这个在某些情况下是否会导致加载过程因长度突然变大导致换行，加载完成后取消换行的行为出现 🤔 (因为在使用antd中会出现这种情况 感觉不太友好~)

**Comment by Lonely-shang** [comment]
我觉得  可以在背景上面  加一个移动的光条

**Comment by kagol** [comment]
Fixed by @XiaoRIGE on #1434
