### ISSUE TITLE
🐛 [Bug]: DatePickerPro打开日历下拉面板时，不应该闪现两个滚动条

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#1430]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/date-picker-pro/

官网第一个demo即可复现该问题：

![image](https://user-images.githubusercontent.com/9566362/200108185-f1ffd5dc-eddc-437b-89d2-801ee0aa0a46.png)

### Step to reproduce

https://vue-devui.github.io/components/date-picker-pro/

- 点击日期选择器输入框
- 弹出日历面板下拉框
- 此时会闪现两个滚动条，我觉得不应该出现滚动条，滚动条应该是鼠标移到相应的区域才出现

![image](https://user-images.githubusercontent.com/9566362/200108185-f1ffd5dc-eddc-437b-89d2-801ee0aa0a46.png)

**Comment by Whbbit1999** [comment]
DatePickPro组件在第一次加载时没有判断 是否有滚动（ Math.abs(newScrollTop - state.scrollTop) !== 0） 的条件

**Comment by Whbbit1999** [comment]
DatePickPro组件在第一次加载时没有判断 是否有滚动（ Math.abs(newScrollTop - state.scrollTop) !== 0） 的条件

**Comment by Whbbit1999** [comment]
#1431 解决，应该是没有对初次打开面板时的条件做判断导致的，加上对 (Math.abs(newScrollTop - state.scrollTop) !== 0) 就好啦
