### ISSUE TITLE
🐛 [Bug]: 分页组件切换pageSize时，获取不到最新的pageSize值

### ISSUE THREAD

**Issue by zhaoShijuan** [DevCloudFE/vue-devui#1435]
### Version

v1.3.1

### Vue Version

v3.2.25

### Link to minimal reproduction

可以直接参考vue-devui文档内pagination组件示例-[多种配置](https://vue-devui.github.io/components/pagination/#%E5%A4%9A%E7%A7%8D%E9%85%8D%E7%BD%AE)

### Step to reproduce

按照提供的链接跳转到【pagination组件的多种配置】示例，打开控制台，切换pageSize大小，控制台输出以下日志：
```JavaScript
undefined 'pageSizeChangeWithoutFix'
```

### What is expected

pagination组件的page-size-change事件能够准确地抛出当前切换的pageSize值

### What is actually happening

根据vue-devui.es.js代码跟踪，发现pageSizeChange函数接受的是个PointerEvent对象，此对象中并没有value字段。
根据devUi源码查看到是因：page-size.tsx中触发pageSizeChange时未传递当前的item值导致。

### Any additional comments (optional)

如果确定是个bug，我申请参与修改此bug

**Comment by GaoNeng-wWw** [comment]
欢迎提交pr
