### ISSUE TITLE
🐛 [Bug]: Mention组件设置position为top，输入第一个字符列表选项没有贴近输入框

### ISSUE THREAD

**Issue by hxj9102** [DevCloudFE/vue-devui#1439]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://devcloudfe.github.io/devui-playground/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDE+XG4gICAgSGVsbG8sIERldlVJIVxuICA8L2gxPlxuICA8aDE+XG4gICAgSGVsbG8sIERldlVJIVxuICA8L2gxPlxuICA8aDE+XG4gICAgSGVsbG8sIERldlVJIVxuICA8L2gxPlxuICA8ZC1tZW50aW9uIDpzdWdnZXN0aW9ucz1cInN1Z2dlc3Rpb25zXCIgcG9zaXRpb249XCJ0b3BcIj48L2QtbWVudGlvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBzZXR1cERldnVpIH0gZnJvbSAnLi9kZXZ1aS5qcydcblxuLy8gZG9uJ3QgcmVtb3ZlXG5zZXR1cERldnVpKClcbiAgXG4gIGNvbnN0IHN1Z2dlc3Rpb25zID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgdmFsdWU6ICdqYXZhc2NyaXB0JyxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIHZhbHVlOiAnVnVlJyxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIHZhbHVlOiAnUmVhY3QnLFxuICB9LFxuICB7XG4gICAgaWQ6IDQsXG4gICAgdmFsdWU6ICdBbmd1bGFyJyxcbiAgfSxcbl07XG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e1wiZGV2dWktdGhlbWVcIjpcImh0dHBzOi8vdW5wa2cuY29tL2RldnVpLXRoZW1lQGxhdGVzdC9pbmRleC5lcy5qc1wiLFwidnVlLWRldnVpXCI6XCJodHRwczovL3VucGtnLmNvbS92dWUtZGV2dWlAbGF0ZXN0L3Z1ZS1kZXZ1aS5lcy5qc1wiLFwidnVlXCI6XCJodHRwczovL3VucGtnLmNvbS92dWVAbGF0ZXN0L2Rpc3QvdnVlLmVzbS1icm93c2VyLmpzXCIsXCJ2dWUtcm91dGVyXCI6XCJodHRwczovL3VucGtnLmNvbS92dWUtcm91dGVyQGxhdGVzdC9kaXN0L3Z1ZS1yb3V0ZXIuZXNtLWJyb3dzZXIuanNcIixcIkBmbG9hdGluZy11aS9kb21cIjpcImh0dHBzOi8vdW5wa2cuY29tL0BmbG9hdGluZy11aS9kb21AbGF0ZXN0L2Rpc3QvZmxvYXRpbmctdWkuZG9tLmVzbS5qc1wiLFwiQGZsb2F0aW5nLXVpL2NvcmVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0BmbG9hdGluZy11aS9jb3JlQGxhdGVzdC9kaXN0L2Zsb2F0aW5nLXVpLmNvcmUuZXNtLmpzXCIsXCJAdnVldXNlL2NvcmVcIjpcImh0dHBzOi8vdW5wa2cuY29tL0B2dWV1c2UvY29yZUBsYXRlc3QvaW5kZXgubWpzXCIsXCJAdnVlL2RldnRvb2xzLWFwaVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9kZXZ0b29scy1hcGlAbGF0ZXN0L2xpYi9lc20vaW5kZXguanNcIixcIkB2dWV1c2Uvc2hhcmVkXCI6XCJodHRwczovL3VucGtnLmNvbS9AdnVldXNlL3NoYXJlZEBsYXRlc3QvaW5kZXgubWpzXCIsXCJ2dWUtZGVtaVwiOlwiaHR0cHM6Ly91bnBrZy5jb20vdnVlLWRlbWlAbGF0ZXN0L2xpYi9pbmRleC5tanNcIn19In0=

### Step to reproduce

1. 设置position为top
2. 输入@j
![image](https://user-images.githubusercontent.com/58357112/202180378-0738b2d9-80d1-42b6-90b1-41a7e1f1c39f.png)

### What is expected

期待搜索列表选项贴近输入框
![image](https://user-images.githubusercontent.com/58357112/202180566-0f084c28-6324-4d5e-b33e-70bd9ad2a6aa.png)

**Comment by kagol** [comment]
Fixed by @hxj9102 on #1442
