### ISSUE TITLE
🐛 [Bug]: table组件勾选行时，会触发行点击与单元格点击事件

### ISSUE THREAD

**Issue by zhaoShijuan** [DevCloudFE/vue-devui#1446]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

官网-Table表格组件-[表格交互](https://vue-devui.github.io/components/table/#%E8%A1%A8%E6%A0%BC%E4%BA%A4%E4%BA%92)

### Step to reproduce

1. 打开控制台，点击某行复选框
2. 会发现控制台输出中包含`checked-change`事件触发与`row-click`、`cell-click`触发

### What is expected

复选框改变时，因只触发`checked-change`事件，排查代码发现`row-click`、`cell-click`被触发原因：
checkbox组件为label绑定的click事件中，未阻止冒泡，导致点击冒泡到cell与row元素上

### Any additional comments (optional)

不知是否属于bug

**Comment by kagol** [comment]
Fixed by @zhaoShijuan on #1447
