### ISSUE TITLE
🐛 [Bug]: Notification组件的duration设置为0时，当鼠标移出时会提示自动消失

### ISSUE THREAD

**Issue by xiaogonggong-w** [DevCloudFE/vue-devui#1468]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

Notification全局通知组件-[超时时间](https://vue-devui.github.io/components/notification/#%E8%B6%85%E6%97%B6%E6%97%B6%E9%97%B4)，根据描述通过 **duration参数设置超时时间，单位ms，默认3000 ms后自动关闭，设置为0则不会自动关闭。** 用户必须在主动点击关闭按钮之后才会消失。

### Step to reproduce

1.超时时间-设置duration为0
2.鼠标移入通知后再移除发现Notification自动消失

**Comment by kagol** [comment]
Fixed by @xiaogonggong-w on #1469
