### ISSUE TITLE
🐛 [Bug]: 组件demo中，点击复制代码片段之后，文字消失

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#1524]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

[https://vue-devui.github.io/components/button/](https://vue-devui.github.io/components/button/)

组件demo中，点击复制代码片段之后，文字消失。

![image](https://user-images.githubusercontent.com/9566362/211127991-9bd9cd24-0f45-46d2-b8d6-a4bb77f41b9e.png)

### Step to reproduce

[https://vue-devui.github.io/components/button/](https://vue-devui.github.io/components/button/)

组件demo中，点击复制代码片段之后，文字消失。

### What is expected

建议点击“复制代码片段”按钮之后，显示类似"Copied!"或者"复制成功"之类的文案，过一会文案再自动更改会“复制代码片段”。

**Comment by Whbbit1999** [comment]
lang.ts文件中缺失复制成功字段，已经提交pr

**Comment by kagol** [comment]
Fixed by @Whbbit1999 on #1532
