### ISSUE TITLE
🐛 [Bug]: 网站部署之后，button组件渲染失败

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#1526]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

使用dev分支最新代码部署测试网站：[https://vue-devui.gitee.io/components/button/](https://vue-devui.gitee.io/components/button/)

发现button组件不渲染，控制台报错：

```
https://vue-devui.gitee.io/vue-devui/packages/devui-vue/docs/components/button/shape.vue net::ERR_ABORTED 404 (Not Found)
```

应该跟近期的 #1520  文档优化有关，可能是文件路径处理不当导致的。

![image](https://user-images.githubusercontent.com/9566362/211128387-ca641910-2633-4827-8a6b-d7292bbdc67c.png)

### Step to reproduce

使用dev分支最新代码部署测试网站：[https://vue-devui.gitee.io/components/button/](https://vue-devui.gitee.io/components/button/)

发现button组件不渲染，控制台报错：

```
https://vue-devui.gitee.io/vue-devui/packages/devui-vue/docs/components/button/shape.vue net::ERR_ABORTED 404 (Not Found)
```

**Comment by hxj9102** [comment]
![image](https://user-images.githubusercontent.com/58357112/212019946-ef599e75-923b-4ba6-ba05-03d5db38c240.png)
另发现其他组件的描述的渲染位置发生错误
