### ISSUE TITLE
🐛 [Bug]: The demo description of Button is not rendered

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#1534]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

The demo description of Button is not rendered:
[https://vue-devui.github.io/components/button/](https://vue-devui.github.io/components/button/)

<img width="944" alt="image" src="https://user-images.githubusercontent.com/9566362/212462245-e18405b2-28a5-4655-a60b-07b992dfa91c.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/9566362/212462203-7d6efa97-d690-4730-89db-20680f2e0b63.png">

### Step to reproduce

The demo description of Button is not rendered:
[https://vue-devui.github.io/components/button/](https://vue-devui.github.io/components/button/)

**Comment by Whbbit1999** [comment]
button组件文档使用的是vuefile渲染，和其他组件使用组件代码渲染使用的方法不同。我这里改了一下可以渲染出来了，但是对于markdown中的html标签不会进行渲染

**Comment by Whbbit1999** [comment]
在 block-plugin.ts 文件中markdown进行转换后进行了UrlEncode编码， 在Demo.vue中使用UrlEncode解码进行渲染时，\<br\\>标签不会进行渲染

**Comment by GaoNeng-wWw** [comment]
Whbbit1999 resolve this problem in pull request #1537
