### ISSUE TITLE
🐛 [Bug]: Menu菜单路由模式下无法监听路由变化更改选中

### ISSUE THREAD

**Issue by peiyanlu** [DevCloudFE/vue-devui#1538]
### Version

1.5.0

### Vue Version

3.2.45

### Link to minimal reproduction

无

### Step to reproduce

无

**Comment by GaoNeng-wWw** [comment]
https://github.com/DevCloudFE/vue-devui/pull/1542

最初api设计的有些问题，应该提供select属性。监听router变化，更改default-selet-keys的值即可。后面可能会有一次break change大概就是加一个select属性，把default-select-keys删掉或者功能合并到select属性里
