### ISSUE TITLE
🐛 [Bug]: horizontal模式menu菜单报错

### ISSUE THREAD

**Issue by liuxiaodi01** [DevCloudFE/vue-devui#1540]
### Version

1.5.0

### Vue Version

3.2.45

### Link to minimal reproduction

https://vue-devui.gitee.io/components/menu/#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95
F12查看 点击 报错 

### Step to reproduce

1.示例代码报错 
2.复制粘贴menu基本用法 （horizontal）

### What is expected

点击menu-item执行

### What is actually happening

 报错  Cannot read properties of undefined (reading 'length')

**Comment by GaoNeng-wWw** [comment]
收到，近日会修复
