### ISSUE TITLE
🐛 [Bug]: 按需自动导入部分组件文件缺失报错

### ISSUE THREAD

**Issue by ALoneMonster** [DevCloudFE/vue-devui#1578]
### Version

1.5.3

### Vue Version

3.2.47

### Link to minimal reproduction

```text
Failed to resolve import "vue-devui/menu-item/index.es.js" from "src\components\TopMenu.vue". Does the file exist?
09:46:35 [vite] Internal server error: Failed to resolve import "vue-devui/menu-item/index.es.js" from "src\components\TopMenu.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/document/IT/python_project/MOSYNX/iceberg/tools/log-web/src/components/TopMenu.vue:2:54    
```

![image](https://github.com/DevCloudFE/vue-devui/assets/51921828/4017754d-31c1-4595-95a1-7fd185187931)

- 目录下寻找过, 的确不存在 `vue-devui/menu-item/index.es.js`, menu-item 的定义似乎写在了  `vue-devui/menu/index.es.js` 里, 如上图. 其它组件应该也有类似问题

### Step to reproduce

1. vite 创建 vue3 项目, 按官方文档配置好组件按需自动导入
2. 在 APP.vue 文件中写内容如下
```vue
<template>
    <d-menu mode="horizontal">
        <d-menu-item key="logo">TEST</d-menu-item>
    </d-menu>
</template>
```
3. 运行 vue 项目

### What is expected

解决bug, 检查其它组件是否存在类似情况

**Comment by GaoNeng-wWw** [comment]
有一个相同的issue：https://github.com/DevCloudFE/vue-devui/issues/1554

问题已由 田主 [banlify](https://github.com/banlify) 提交 https://github.com/antfu/unplugin-vue-components/pull/614 修复

但是PR614至今没有被合并，请尝试手动导入
