### ISSUE TITLE
🐛 [Bug]: Menu菜单激活状态异常

### ISSUE THREAD

**Issue by peiyanlu** [DevCloudFE/vue-devui#1585]
### Version

1.5.3

### Vue Version

3.2.47

### Link to minimal reproduction

暂无

### Step to reproduce

先通过点击的方式激活子菜单，再通过面包屑等方式激活一个路由，发现虽然菜单中选中并高亮了对应的子菜单，但是对应的父级菜单的高亮状态类（devui-menu-active-parent）依旧在通过点击激活的子菜单的父级

### What is expected

菜单的父级状态跟随子级变化而变化

### What is actually happening

![image](https://github.com/DevCloudFE/vue-devui/assets/37688666/bf658e93-db9f-422f-9b08-83bd8e6cf6f6)

如图所示，先在内容二中通过点击子菜单的方式激活了内容二，然后通过tab页激活了子菜单‘内容一er’，但是他的父级没有添加类名 devui-menu-active-parent

**Comment by GaoNeng-wWw** [comment]
感谢您的issue~

可以贴一下结构吗，方便我们复现一下

**Comment by peiyanlu** [comment]
<img width="472" alt="Snipaste_2023-06-14_15-54-35" src="https://github.com/DevCloudFE/vue-devui/assets/37688666/667dfafd-eef1-4582-b3c1-47d2695500e3">
这是菜单数据的结构

**Comment by GaoNeng-wWw** [comment]
umm....不建议你单独使用`<sub-menu>`与`<menu-item>`，如果希望实现侧边栏的话`menu`和`accordion`都可以满足你的要求。

如果用menu组件，最好是[参考这里](https://vue-devui.github.io/components/menu/#%E5%9E%82%E7%9B%B4%E8%8F%9C%E5%8D%95)

@peiyanlu

**Comment by peiyanlu** [comment]
好的  有时间我会再试一下，另外accordion好像没有专门的文档，只在布局案例里面出现了

**Comment by GaoNeng-wWw** [comment]
accordion应该是被废弃了，但是你仍然可以使用。

如果没有什么问题的话，我会关闭这个ISSUE~
