### ISSUE TITLE
tooltip mouseLeaveDelay 和 mouseEnterDelay 类型为string，个人建议应该为number

### ISSUE THREAD

**Issue by to0simple** [DevCloudFE/vue-devui#161]

**Comment by kagol** [comment]
@to0simple 我看文档已经改了：

[https://vue-devui.github.io/components/tooltip/](https://vue-devui.github.io/components/tooltip/)

**Comment by to0simple** [comment]
> @to0simple 我看文档已经改了：
> 
> https://vue-devui.github.io/components/tooltip/

ok
