### ISSUE TITLE
官方文档页面空白

### ISSUE THREAD

**Issue by redshade** [DevCloudFE/vue-devui#1619]
搜索某个组件，进入的链接包含#锚点，这种链接再次刷新页面会报错导致页面空白
https://vue-devui.github.io/components/input//#input-%E8%BE%93%E5%85%A5%E6%A1%86

![image](https://github.com/DevCloudFE/vue-devui/assets/17384678/2fa86af1-fc3b-4113-98e6-59ba9f24244c)

**Comment by Whbbit1999** [comment]
我试着改了一下，在本地测试没有什么问题了。应该是地址栏中出现了两个`/`导致的路由解析错误

**Comment by fu050409** [comment]
此 issue 看起来已经被解决
