### ISSUE TITLE
🐛 [Bug]: Search组件maxLength默认值不应该是0

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#166]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

组件地址：
[https://vue-devui.github.io/components/search](https://vue-devui.github.io/components/search)

### Step to reproduce

由于maxLength默认值设置为0，直接如下使用将无法在输入框输入字符：
```
<d-search  v-model="searchText"></d-search>
```

**Comment by SituC** [comment]
@all-contributors please add @SituC  for code
