### ISSUE TITLE
✨ [Feature]: MarkDown编辑器不支持数学公式的渲染

### ISSUE THREAD

**Issue by mindhacker0** [DevCloudFE/vue-devui#1662]
### What problem does this feature solve

devui的md编辑器可以支持数学公式的编写和渲染

### What does the proposed API look like

$\sum_{n=1}^{\infty}\frac{1}{n^{2k}}=\frac{\pi^2}{6}$
在devui的md编辑器不会渲染，在github或其它地方可以。

**Comment by CoderSerio** [comment]
我想尝试修复这个问题 @Julinear

**Comment by CoderSerio** [comment]
好吧，看起来已经在 Pull #1753 中解决过了
