### ISSUE TITLE
markdown编辑器没有实现列表内勾选渲染🐛 [Bug]: 

### ISSUE THREAD

**Issue by mindhacker0** [DevCloudFE/vue-devui#1697]
### Version

1.5.12

### Vue Version

3.3.4

### Link to minimal reproduction

![image](https://github.com/DevCloudFE/vue-devui/assets/47465447/a95d5072-0171-4880-8c72-cb729062aaa8)

### Step to reproduce

在markdown编辑器的表格内输入选择框，没有渲染出来

### What is expected

![image](https://github.com/DevCloudFE/vue-devui/assets/47465447/722e9b1a-adb1-497d-a871-217975d5b1b5)

**Comment by GreatZPP** [comment]
V1.5.14版本已提供插件可配置，https://vue-devui.github.io/components/editor-md/#checkbox-%E6%B8%B2%E6%9F%93 可参考进行配置一下
