### ISSUE TITLE
🐛 [Bug]: d-option 组件用不了

### ISSUE THREAD

**Issue by xsmvp** [DevCloudFE/vue-devui#1698]
### Version

1.5.4

### Vue Version

3.3.4

### Link to minimal reproduction

![81692864727_ pic](https://github.com/DevCloudFE/vue-devui/assets/23623029/fd678339-4fb0-4864-8f1b-1a10f7686e26)
如官方案例一样用 d-option 组件，会出现如下报错，查看本地的包没有 option 文件夹

![31692863982_ pic](https://github.com/DevCloudFE/vue-devui/assets/23623029/9b840dc9-5b9e-465c-915c-a9540b4c5ab6)

### Step to reproduce

如案例代码方式调用

**Comment by GreatZPP** [comment]
d-option属于select组件，在select目录下哦

**Comment by xsmvp** [comment]
> 

你看看报错 路径没有在 select 下是跟 select 同级的，而且我看了 select 下也没有 option

**Comment by GreatZPP** [comment]
是用来按需引入插件么 当前使用该插件引入可能存在当前问题

**Comment by xingyan95** [comment]
你是不是用的`unplugin-vue-components/resolvers`这个按需引入的插件之后，出现的这个错误呀？
d-option 组件是 select 的子组件，这个按需引入插件默认都是从组件根目录查找，针对子组件的按需引入，还未更新 resolvers 去适配，并且 d-option 也未放到组件的根目录，所以出现这个错误。
可以先通过手动按需引入的方式规避下~  我们后续会把按需引入这块修正下~

**Comment by xsmvp** [comment]
> 你是不是用的`unplugin-vue-components/resolvers`这个按需引入的插件之后，出现的这个错误呀？ 利用`unplugin-vue-components/resolvers`按需引入的插件当前部分组件会存在此问题。可以先通过手动按需引入的方式规避下~ 我们后续会把按需引入这块修正下~

对头 是自动引入的
