### ISSUE TITLE
🐛 [Bug]: Markdown MD 编辑器组件的预览模式 无法区分无序列表和任务列表

### ISSUE THREAD

**Issue by zwxs** [DevCloudFE/vue-devui#1756]
### Version

1.5.15-hotfix.4

### Vue Version

3.3.4

### Link to minimal reproduction

Markdown MD 编辑器 任务列表和无序列表没有类名区分
无法分别修改无序列表和任务列表的样式
需求想要单独去掉任务列表的 list-style：none 但是会和无序列表冲突
![image](https://github.com/DevCloudFE/vue-devui/assets/18496323/f43924ac-b1b1-4627-8b24-e83611151458)
![image](https://github.com/DevCloudFE/vue-devui/assets/18496323/d58fe7b2-3226-4cb5-8d86-600bc53bacd5)

### Step to reproduce

希望能分别使用类名区分一下渲染的有序无序任务列表

**Comment by GreatZPP** [comment]
当前1.6.0版本 默认checkbox工具已经去除+语法 不引入默认列表样式
