### ISSUE TITLE
🐛 [Bug]: d-button 大小不一致 

### ISSUE THREAD

**Issue by ghost** [DevCloudFE/vue-devui#1763]
### Version

1.6.0

### Vue Version

3.3.4

### Link to minimal reproduction

 <d-button variant="solid" color="primary"> Primary </d-button>

### Step to reproduce

执行npm create vue@latest 创建一个vue3+ts+router+pinia的项目 然后按照https://vue-devui.github.io/quick-start/这个来引入组件 默认的button按钮的样式很小
![image](https://github.com/DevCloudFE/vue-devui/assets/105619736/4d7c7def-169f-44d5-a734-442f3373d383)
![image](https://github.com/DevCloudFE/vue-devui/assets/105619736/a63f4fa7-d3d5-4f41-ac8f-0203d1bfb614)

### What is expected

我希望这是一个正常大小的按钮

**Comment by LianXiaoxiang** [comment]
并没有开缩放

**Comment by LianXiaoxiang** [comment]
![image](https://github.com/DevCloudFE/vue-devui/assets/105619736/944a7ba4-c2c4-42b3-b1e4-e9d7287fd930)

**Comment by LianXiaoxiang** [comment]
在class类里面 看到.devui-button--md没有高度 但是在官网的案例里面是有这个样式的
![image](https://github.com/DevCloudFE/vue-devui/assets/105619736/fdf04601-6473-4770-bdc9-7986c7fc8a58)
![image](https://github.com/DevCloudFE/vue-devui/assets/105619736/5de5f4e5-77d8-47cc-9b9e-7e57cc7d84bc)
于是自己加了一个样式

**Comment by GreatZPP** [comment]
https://github.com/DevCloudFE/vue-devui/pull/1692 对应修改已合入 等待版本发布
