### ISSUE TITLE
✨ [Feature]: category search 支持文本类型的自动获取文本输入框的焦点

### ISSUE THREAD

**Issue by aolinpk** [DevCloudFE/vue-devui#1842]
### What problem does this feature solve

category search 支持文本类型的自动获取文本输入框的焦点。华为云有该功能。点击的字段是可输入类型的组件时自动聚焦到对应输入组件。
![image](https://github.com/DevCloudFE/vue-devui/assets/29527991/28cb715c-59bb-4569-b639-8b1c9b6fdcd3)

### What does the proposed API look like

这算易用性优化，希望可以自动实现。

**Comment by aolinpk** [comment]
已提交PR

**Comment by fu050409** [comment]
@aolinpk 这个 issue 看起来是已经解决了？
