### ISSUE TITLE
🐛 [Bug]: InputNumber数字输入框，去除掉值之后失焦/确认之后会变成数值0，应该为空

### ISSUE THREAD

**Issue by aolinpk** [DevCloudFE/vue-devui#1843]
### Version

1.6.18

### Vue Version

3.3.4

### Link to minimal reproduction
官方文档即可复现

### Step to reproduce
当inputNumber框作为一个非必填输入时他理应可以清空值。但是devui组件中的InputNumebr 用户手动删除值失焦或者确认时会变回0。
![image](https://github.com/DevCloudFE/vue-devui/assets/29527991/79b17121-9adb-4eaa-af7b-1011f6578d2f)
![image](https://github.com/DevCloudFE/vue-devui/assets/29527991/5e7eb38a-4738-426f-bd66-5f74827b5520)

### What is expected
在inputNumber组件中删除已输入的值可以变为空。

### What is actually happening
删除掉值之后变成了0

**Comment by fu050409** [comment]
此 issue 相关的 PR 已经被 Merge，故关闭此 issue。
