### ISSUE TITLE
✨ [Feature]: 希望action-timeline的icon可以支持插槽的形式嵌入

### ISSUE THREAD

**Issue by aolinpk** [DevCloudFE/vue-devui#1846]
### What problem does this feature solve

项目中的图标不是伪类形式的，希望可以通过插槽的方式注入显示。目前组件已经开放了标题和内容的插槽建议也加入图标的插槽。
![image](https://github.com/DevCloudFE/vue-devui/assets/29527991/6b5c66db-b219-4d28-a467-477f61dc7c6f)

### What does the proposed API look like

API name: iconContent

**Comment by aolinpk** [comment]
本周内会提交PR

**Comment by fu050409** [comment]
和此 issue 关联的 PR 已经被 Merge，故关闭此 issue。

另外，你可以依照 GitHub 的标准在你的 Pull Request 中的描述文本中加入`Resolved #1880`（也可以用`Fix`、`Resolves`等关键字，参考 [GitHub 官方教程](https://docs.github.com/zh/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)）字样来链接你的 PR 和你解决的 issue，这样在 PR 被合并时 issue 会被一并关闭 :)

_Originally posted by @fu050409 in https://github.com/DevCloudFE/vue-devui/issues/1880#issuecomment-2177949015_
