### ISSUE TITLE
✨ [Feature]: 更新开发环境版本

### ISSUE THREAD

**Issue by fu050409** [DevCloudFE/vue-devui#1852]
### What problem does this feature solve

在运行`Vue-DevUI`项目本体的时候，我意识到我们的开发环境存在严重的版本断层问题。

经测试，Nodejs 版本为14的时候存在部分语法不支持的问题，Nodejs 18可以正常运行，但部分组件存在功能性异常，Nodejs 20与pnpm 6配合不佳。目前测试表明只有在`Nodejs 16`及`pnpm@6`下，项目可以稳定运行。

### What does the proposed API look like

我们是否有升级当前环境版本的计划呢？旧版本的软件通常会存在安全漏洞，这些漏洞可能会被恶意利用，同时，旧版本不再被社区继续维护（例如我们使用`pnpm 6.x`，然而最新版本是`9.1.2`，很多功能存在不兼容，而`pnpm 6.x`则已经不再被pnpm官方维护），使用最新版本的环境可以更恰当的与相关社区保持一致，节省开发时间。

如果这是计划内的内容，我或许可以尝试为此工作 :)

**Comment by CoderSerio** [comment]
+1

**Comment by Julinear** [comment]
需求合理，可以尝试贡献处理一下哦~ @fu050409
