### ISSUE TITLE
✨ [Feature]:  devui的tree组件，devui-tree__node不支持有选中的类名

### ISSUE THREAD

**Issue by wwt444** [DevCloudFE/vue-devui#1880]
### What problem does this feature solve

devui的tree组件，选中节点的类名目前加在devui-tree__node-content上，希望父级节点devui-tree__node也能添加一个选中的类名，扩展我们对选中父级节点的样式修改

### What does the proposed API look like

devui的tree组件，选中节点的类名只加在子节点devui-tree__node-content上
![image](https://github.com/DevCloudFE/vue-devui/assets/49834266/5f26b5d2-41d7-48cb-b0c7-dc9fc5964b63)
![image](https://github.com/DevCloudFE/vue-devui/assets/49834266/438ebe2c-066e-4742-ac24-4ed0094117f4)

**Comment by wwt444** [comment]
#1881 已提交PR

**Comment by fu050409** [comment]
此 issue 关联的 PR 已经被合并，故关闭此 issue。

另外，@wwt444  你可以依照 GitHub 的标准在你的 Pull Request 中的描述文本中加入`Resolved #1880`（也可以用`Fix`、`Resolves`等关键字，参考 [GitHub 官方教程](https://docs.github.com/zh/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)）字样来链接你的 PR 和你解决的 issue，这样在 PR 被合并时 issue 会被一并关闭 :)
