### ISSUE TITLE
✨ [Feature]: 你的存储库似乎被盗用了

### ISSUE THREAD

**Issue by yang0916** [DevCloudFE/vue-devui#1901]
### What problem does this feature solve

你的存储库已被同步到gitcode中了，你可以去查看一下，不知是否是您本人授权后被同步的

### What does the proposed API look like

你的存储库已被同步到gitcode中了，你可以去查看一下，不知是否是您本人授权后被同步的
查看网址：https://gitcode.com/DevCloudFE/vue-devui/overview

**Comment by fullstackpeng** [comment]
点进用户名是404，但是仓库地址可以看到

**Comment by yang0916** [comment]
> 点进用户名是404，但是仓库地址可以看到

![1719541962905](https://github.com/DevCloudFE/vue-devui/assets/51697575/461218c0-f1c9-4407-bfae-1826c74797eb)
是可以看到的

**Comment by GreatZPP** [comment]
你好，谢谢友好提醒，关于gitcode的同步我们是知晓的，在后续的演进中，如果可以，我们也会尝试更多使用gitcode平台。
