### ISSUE TITLE
✨ : 库是不是不维护了？

### ISSUE THREAD

**Issue by mustars** [DevCloudFE/vue-devui#1905]
### What problem does this feature solve

这个库是不是不维护了？跟devui angular落下太多了...

### What does the proposed API look like

1

**Comment by GreatZPP** [comment]
当前特性是有在继续演进，具体是在哪方面特性呢

**Comment by mustars** [comment]
表单Cascader、TreeSelect组件没有；Select、InputNumber组件无法键盘操作；tabs拖动排序；
DataGrid列宽记忆、列拖拽、行拖拽、批量行拖拽未实现；
最重要是组件内未加入分页，组件只实现本地筛选、排序，这两个动作都会引起分页及滚动条的变化，需要自己实现。
强烈建议本地分页、筛选、排序由组件内完成，服务器则由开发者自控；可参考ant框架。

22年计划V2.0版本，可惜参与者较低。

**Comment by zyxiaoxiao** [comment]
早就没维护了，没人用

**Comment by GreatZPP** [comment]
一直在维护的，可以看看最近的新发版本和组件，最近也新增了一些更多的能力
