### ISSUE TITLE
✨ [Feature]: 怎么回事  2年没更新了？放弃了vue 版本？ 还是1.6.21

### ISSUE THREAD

**Issue by zyxiaoxiao** [DevCloudFE/vue-devui#1906]
### What problem does this feature solve

连bug 都没人解决

### What does the proposed API look like

连bug 都没人解决

**Comment by GreatZPP** [comment]
一直在更新哦，1.6.21也是最近发布的版本

**Comment by zyxiaoxiao** [comment]
有没有更新 大家都知道

**Comment by zyxiaoxiao** [comment]
你也没必要老是关闭问题

**Comment by GreatZPP** [comment]
是有什么需要解决的问题么，我在issue中没有找到你提的issue，更新也可以看看PR合并记录，最近很多组件都有进行缺陷修复，并且发布了新的组件，所以2年未更新结论从何得出呢
