### ISSUE TITLE
🐛 [Bug]: input输入框icon展示有问题

### ISSUE THREAD

**Issue by CatsAndMice** [DevCloudFE/vue-devui#191]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/input/#%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95
input密码框输入内容，图标重叠在一起

### Step to reproduce

![image](https://user-images.githubusercontent.com/58327088/152943303-1aa8d6f4-23de-4a56-b353-492a7b7cace5.png)
输入内容，图标好像重叠在一起了

**Comment by tycsbs** [comment]
这个问题已经修复了 [pr地址](https://github.com/DevCloudFE/vue-devui/pull/196), 这个issues可以关了
