### ISSUE TITLE
根据commit message，自动生成changelog

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#217]
在dev分支合入main分支的时候，根据commit message，自动生成changelog，内容放到子包的`CHANGELOG.md`文件中

**Comment by CatsAndMice** [comment]
这个我可以去研究研究

**Comment by gebilaofan** [comment]
认领一下这个

**Comment by gebilaofan** [comment]
![image](https://user-images.githubusercontent.com/46524158/161018290-e9a6778d-4d66-49c9-b404-6bf8132d41b9.png)


已经存在 changelog 文件生成

**Comment by kagol** [comment]
fixed by @banlify on #268
