### ISSUE TITLE
🐛 [Bug]: [d-panel]API和参数问题

### ISSUE THREAD

**Issue by xingyan95** [DevCloudFE/vue-devui#219]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/panel/

### Step to reproduce

1. 【基本用法】的第二个demo和第三个展开收起状态相关联。
2. 【多种类型】的`info`和`primary`类型的 demo 相关联，`success`和`warning`类型的 demo 相关联。
3. `beforeToggle` 参数类型建议改成`(done: () => void) => void`，业务在执行完同步或者异步操作之后，根据执行结果选择是否调用`done`函数，调用`done`则表示改变折叠状态，不调用则不改变。
4. `toggle` 事件应该通过 `Emit` 触发，不应该通过 `props` 传入。

**Comment by GaoNeng-wWw** [comment]
`beforeToggle ` 是面板折叠状态改变前的回调函数，可以有返回值，当返回值为false时面板不允许折叠。

**Comment by xingyan95** [comment]
> `beforeToggle ` 是面板折叠状态改变前的回调函数，可以有返回值，当返回值为false时面板不允许折叠。

回调函数里面需要支持的异步类型不太可控，回调函数中的异步可以是`Promise`、`setTimeout`等，组件内部需要处理的逻辑会比较多。通过提供`done`函数的方式，组件内部可以不用关注用户用的哪种异步，只需要保证用户在执行完异步之后，调用`done`能够改变折叠状态，不调用`done`则不会改变即可。

**Comment by GaoNeng-wWw** [comment]
> > `beforeToggle ` 是面板折叠状态改变前的回调函数，可以有返回值，当返回值为false时面板不允许折叠。
> 
> 回调函数里面需要支持的异步类型不太可控，回调函数中的异步可以是`Promise`、`setTimeout`等，组件内部需要处理的逻辑会比较多。通过提供`done`函数的方式，组件内部可以不用关注用户用的哪种异步，只需要保证用户在执行完异步之后，调用`done`能够改变折叠状态，不调用`done`则不会改变即可。

嗯，确实是一个不错的方法。但或许我不会用done这个名称，我认为```preventCollapsed```或许更好，因为这样可以更加的语义化。或者我们两者都要？

**Comment by xingyan95** [comment]
> > > `beforeToggle ` 是面板折叠状态改变前的回调函数，可以有返回值，当返回值为false时面板不允许折叠。
> > 
> > 
> > 回调函数里面需要支持的异步类型不太可控，回调函数中的异步可以是`Promise`、`setTimeout`等，组件内部需要处理的逻辑会比较多。通过提供`done`函数的方式，组件内部可以不用关注用户用的哪种异步，只需要保证用户在执行完异步之后，调用`done`能够改变折叠状态，不调用`done`则不会改变即可。
> 
> 嗯，确实是一个不错的方法。但或许我不会用done这个名称，我认为`preventCollapsed`或许更好，因为这样可以更加的语义化。或者我们两者都要？

1. `preventCollapsed`是阻止折叠吧，语义上来说可能有些限制了，`beforeToggle`应该是折叠和展开两种情况都会触发吧。
2. `beforeToggle`的作用应该是在改变折叠状态之前，执行一些操作，操作结束之后，根据执行结果可以选择允许改变折叠状态或者阻止改变，`done`有完毕/结束的意思，表示可以继续执行之前改变折叠状态的动作。
3. `done`我认为更通用一些，在`Modal`、`Drawer`等组件中，都有像`bofore-close`这种和`before-toggle`类似的需求，可以采用同样的思路和命名来实现，这种通用的我觉可以在田主大会上一起讨论下~

**Comment by GaoNeng-wWw** [comment]
> > > > `beforeToggle ` 是面板折叠状态改变前的回调函数，可以有返回值，当返回值为false时面板不允许折叠。
> > > 
> > > 
> > > 回调函数里面需要支持的异步类型不太可控，回调函数中的异步可以是`Promise`、`setTimeout`等，组件内部需要处理的逻辑会比较多。通过提供`done`函数的方式，组件内部可以不用关注用户用的哪种异步，只需要保证用户在执行完异步之后，调用`done`能够改变折叠状态，不调用`done`则不会改变即可。
> > 
> > 
> > 嗯，确实是一个不错的方法。但或许我不会用done这个名称，我认为`preventCollapsed`或许更好，因为这样可以更加的语义化。或者我们两者都要？
> 
> 这个done其实是beforeToggle方法的一个参数，大致使用场景是：
> 
> ```ts
> <d-panel
>   :beforeToggle="beforeToggle"
> ></d-panel>
> 
> const beforeToggle = (done) => {
>   fetch(url).then(({ hasPermission }) => {
>     if (hasPermission) {
>       // 如果有权限则调用 done 回调函数展开面板内容
>       done();
>     } else {
>       // 如果没有权限，则提示没有权限查看折叠面板里面的内容
>     }
>   })
> }
> ```

我打算打一组融合卡，同时保留```return```和```done()```，让用户自己来选择或许会更好一点？
