### ISSUE TITLE
eslint的规则配置与prettier格式化冲突

### ISSUE THREAD

**Issue by zhuchentong** [DevCloudFE/vue-devui#29]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

![6918a74cf00562e4564f9330c8a17d1](https://user-images.githubusercontent.com/4535888/146558042-e808a1bf-f3a0-4533-9e4d-acc65da6f1cc.png)

### Step to reproduce

在项目中定义单行对象即可出现错误提示

```
const data = {item:1}
```

### Any additional comments (optional)

`eslint中·@typescript-eslint/member-delimiter-style`这个中配置为

```
  singleline: {
          delimiter: 'semi',
          requireLast: true
        }
```

要求在对象在单行模式下以分号结尾，但是prettier会自动删除对象结尾的分号，导致`eslint`产生警告

期望删除相关配置，单行不需要以分号结尾

**Comment by kagol** [comment]
@zhuchentong 已修改`.prettierrc`配置，统一加上句尾分号
