### ISSUE TITLE
🥳 欢迎在评论区认领组件

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#297]
Vue DevUI 组件库采取认领机制进行组件的贡献，如果你想成为某个组件的田主，请在评论区评论`认领 xx 组件`，比如：
```
认领 DatePickerPro 组件
```

这样你就是这个组件的田主啦，然后你可以添加微信`devui-official`，让DevUI小助手把你拉到`DevUI田主交流群`，成为田主俱乐部的一员，一起愉快地交流技术、共同成长🎉🎉

期待你的加入！🤝

---

2022.8.14 update

还有以下组件未完成：
1. DragDrop #1035 
3. Dropdown #1041 
5. Modal #1042 
8. DatePickerPro #1045 
9. Form 更新验证规则 #1046 
11. Select #1051 
14. TreeSelect #1054 
18. Table #1058 

-----

9. Anchor #1036 
4. NavSprite - 未启动 #1039 
6. Cascader #1043 
7. CategorySearch - 未启动 #1044 
10. MultiAutoComplete - 未启动 #1050 
12. TimePicker 自定义模板 #1052 
13. Transfer 虚拟滚动 #1053 
15. Dashboard - 未启动 #1055 
16. Gantt - 未启动 #1056 
17. QuadrantDiagram - 未启动 #1057

**Comment by jCodeLife** [comment]
认领 DatePickerPro 组件

**Comment by kagol** [comment]
> 认领 DatePickerPro 组件

收到，已更新花名册，目前该组件有两名田主：

**Comment by kagol** [comment]
目前还有以下组件无主，欢迎认领：
- [Dashboard](https://devui.design/components/zh-cn/dashboard)
- Menu

**Comment by Roading** [comment]
@kagol Dashboard组件我来写

**Comment by GaoNeng-wWw** [comment]
认领Menu

**Comment by kagol** [comment]
> @kagol Dashboard组件我来写

收到，已更新组件花名册

**Comment by kagol** [comment]
> 认领Menu

收到，已更新组件花名册

**Comment by kagol** [comment]
目前以下组件还没有贡献者头像：

1. anchor 
2. nav-sprite
3. tabs
4. alert
5. drawer
6. checkbox
7. date-picker
8. editable-select
9. input-icon
10. tag-input
12. countdown
13. table
14. timeline
15. tree
16. grid

**Comment by gumingWu** [comment]
认领alert

**Comment by kagol** [comment]
> 认领alert

alert组件已经开发完成了，如果发现问题，欢迎一起完善，也欢迎认领其他组件。

**Comment by kagol** [comment]
目前还有以下组件未完成，欢迎@相应的田主一起协作开发：
1. DragDrop 拖拽 @asdlml6 
2. Sticky 便贴 @maizhiyuan
3. Accordion 手风琴 @Pineapple0919 @liuxdi
4. Anchor 锚点 @asian-TMac
5. BackTop 回到顶部 @c0dedance
6. Breadcrumb 面包屑 @naluduo233
7. Dropdown 下拉菜单 @Zcating
8. NavSprite 导航精灵 @flxy1028
9. StepsGuide 操作指引 @pupulus
10. Tabs 选项卡切换 @flxy1028
11. Drawer 抽屉板 @lnzhangsong
12. Tooltip 提示 @zxlfly
13. Cascader 级联菜单 @SituC
14. ColorPicker 颜色选择器 @ErKeLost
15. DatePicker 日期选择器 @mrundef
16. Form 表单 @AlanLee97
17. InputIcon 图标输入框 @mrundef
18. InputNumber 数字输入框 @git-Where
19. Select 下拉选择框 @lookforwhat
20. TimePicker 时间组件器 @qq154239735
21. Transfer 穿梭框 @ForeseeBear
22. TreeSelect 树形选择框 @254311563
23. Carousel 走马灯 @Roading
24. Gantt 甘特图 @liuyingbin
25. List 列表 @xingyan95
26. QuadrantDiagram 象限图 @nowisfuture
27. Table 表格 @Zcating @ivestszheng @georgeleeo_jxd @weban
28. Tag 标签 @c0dedance
29. Tree 树 @faq0192 @linxiang07

**Comment by LadyChatterleyLover** [comment]
认领menu

**Comment by angelanana** [comment]
认领Breadcrumb

**Comment by kagol** [comment]
2022.7.12 update:

目前还有以下组件功能未完成，欢迎认领：
1. [DragDrop 拖拽](https://devui.design/components/zh-cn/dragdrop/demo)
2. [Sticky 便贴](https://devui.design/components/zh-cn/sticky/demo): [滚动容器](https://devui.design/components/zh-cn/sticky/demo#scroll-target)
3. [Anchor 锚点](https://devui.design/components/zh-cn/anchor/demo)
4. [BackTop 回到顶部](): [滚动容器](https://devui.design/components/zh-cn/back-top/demo#back-top-scroll-container)
5. [Breadcrumb 面包屑](https://devui.design/components/zh-cn/breadcrumb/demo): [可下拉](https://devui.design/components/zh-cn/breadcrumb/demo#drop-down-breadcrumbs)  [naluduo233](https://github.com/naluduo233)  [angelanana](https://github.com/angelanana)
6. [Dropdown 下拉菜单](https://devui.design/components/zh-cn/dropdown/demo)
7. [NavSprite 精灵导航](https://devui.design/components/zh-cn/nav-sprite/demo)
8. [StepsGuide 操作指引](https://devui.design/components/zh-cn/steps-guide/demo): [自定义](https://devui.design/components/zh-cn/steps-guide/demo#custom)
9. [Drawer 抽屉板](https://devui.design/components/zh-cn/drawer/demo): [自定义模板](https://devui.design/components/zh-cn/drawer/demo#template)
10. Menu 菜单 [GaoNeng-wWw](https://github.com/GaoNeng-wWw) [LadyChatterleyLover](https://github.com/LadyChatterleyLover)
11. [Mention 提及](https://devui.design/components/zh-cn/mention/demo)
12. [Modal 弹窗](https://devui.design/components/zh-cn/modal/demo)
13. Toast 全局提示: 区别于Notification组件
14. [Cascader 级联菜单](https://devui.design/components/zh-cn/cascader/demo)
15. [CategorySearch 分类搜索](https://devui.design/components/zh-cn/category-search/demo)
16. [DatePickerPro 日期选择器](https://devui.design/components/zh-cn/datepickerPro/demo)
17. [Form 表单](https://devui.design/components/zh-cn/form/demo): [更新校验规则](https://devui.design/components/zh-cn/form/demo#demo-validate-update)
18. [InputNumber 数字输入框](https://devui.design/components/zh-cn/input-number/demo#number-basic): [正则限制](https://devui.design/components/zh-cn/input-number/demo#number-reg)、[小数限制](https://devui.design/components/zh-cn/input-number/demo#decimal-limit)
19. [MultiAutoComplete 多项自动补全](https://devui.design/components/zh-cn/multi-auto-complete/demo)
20. [TreeSelect 树形选择框](https://devui.design/components/zh-cn/tree-select/demo)
21. [Dashboard 仪表盘](https://devui.design/components/zh-cn/dashboard/demo)
22. [Gantt 甘特图](https://devui.design/components/zh-cn/gantt/demo)
23. [QuadrantDiagram 象限图](https://devui.design/components/zh-cn/quadrant-diagram/demo)
24. [Table 表格](https://devui.design/components/zh-cn/datatable/demo): [懒加载](https://devui.design/components/zh-cn/datatable/demo#lazy-loading-of-list-data) [虚拟滚动](https://devui.design/components/zh-cn/datatable/demo#virtual-scroll) [行拖拽](https://devui.design/components/zh-cn/datatable/demo#drag-row) [列拖拽](https://devui.design/components/zh-cn/datatable/demo#column-dragging)
25. [Tree 树](https://devui.design/components/zh-cn/tree/demo): [可拖拽树](https://devui.design/components/zh-cn/tree/demo#drag-and-drop-tree)

**Comment by LadyChatterleyLover** [comment]
认领BackTop，Modal弹窗，Toast，

**Comment by LadyChatterleyLover** [comment]
Mention 提及

**Comment by kagol** [comment]
> 认领BackTop，Modal弹窗，Toast，

收到~

**Comment by T-Tuan** [comment]
认领 Breadcrumb 组件

**Comment by c0dedance** [comment]
认领table 虚拟滚动

**Comment by angelanana** [comment]
认领 tree树组件：可拖拽树， TreeSelect 树形选择框

**Comment by kagol** [comment]
> 认领 tree树组件：可拖拽树， TreeSelect 树形选择框

收到

**Comment by kagol** [comment]
> 认领table 虚拟滚动

收到

**Comment by kagol** [comment]
> 认领 Breadcrumb 组件

收到

**Comment by jecyu** [comment]
认领 Drawer 抽屉--自定义模版

**Comment by jecyu** [comment]
认领 Drawer 抽屉板-自定义模版

**Comment by xzxldl55** [comment]
认领Dashboard组件

**Comment by kagol** [comment]
> 认领Dashboard组件

收到

**Comment by kagol** [comment]
> 认领 Drawer 抽屉板-自定义模版

收到

**Comment by kagol** [comment]
迁移至 #1366

**Comment by cxybd** [comment]
认领multiautocomplete组件
