### ISSUE TITLE
🐛 [Bug]: Overlay组件文档标题缺少英文名字

### ISSUE THREAD

**Issue by xingyan95** [DevCloudFE/vue-devui#313]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/overlay/

### Step to reproduce

![image](https://user-images.githubusercontent.com/11143986/159216768-70821b8f-211e-4ace-b9fc-65c6bed8889b.png)

### What is expected

遮罩层 =》Overlay 遮罩层

**Comment by kagol** [comment]
fixed by @wakaka378 on #360
