### ISSUE TITLE
【Modal】Modal组件拖动时有报错，且点击空白区域无法关闭Modal

### ISSUE THREAD

**Issue by AlanLee97** [DevCloudFE/vue-devui#33]
### Version

v1.0.0-beta.12

### Vue Version

3.1.1

### Link to minimal reproduction

https://vue-devui.github.io/components/modal/

### Step to reproduce

复现步骤
1. 点击打开Modal的按钮
2. 拖动Modal框
3. 控制台报错`app.f1738605.js:4 TypeError: Cannot read property 'deep' of undefined`
![image](https://user-images.githubusercontent.com/42601044/146626041-7e5cb2fb-541b-4023-b635-61994298a74c.png)

**Comment by Zcating** [comment]
dLoading 不是全局指令了，需要单独引入。
