### ISSUE TITLE
🐛 [Bug]: pnpm eslint 报错

### ISSUE THREAD

**Issue by gebilaofan** [DevCloudFE/vue-devui#367]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

暂无

### Step to reproduce

使用`pnpm eslint`命令时出现`typescript`版本错误
![image](https://user-images.githubusercontent.com/46524158/161026642-6cf64adc-1605-4324-80b9-41c1844ec03c.png)

![image](https://user-images.githubusercontent.com/46524158/161026884-a4b707f9-0a40-4876-ba7a-097f5f47baff.png)

项目工作区的`typescript`版本为`4.5.5`  比`eslint`规定的版本高

`SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0`

`node_modules`中`typescript`版本
![image](https://user-images.githubusercontent.com/46524158/161027244-10f26078-fda0-4f99-ab1c-087a739e0372.png)

### What is expected

`eslint`运行不报错

### What is actually happening

```ssh

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.5

Please only submit bug reports when using the officially supported version.
```

**Comment by kagol** [comment]
确实存在问题，可以使用以下命令：
```shell
pnpm cli --filter vue-devui -- code-check -t eslint
```
参考：
https://github.com/DevCloudFE/vue-devui/wiki/DevUI-CLI-%E4%B8%AD-CodeCheck-%E4%BB%A3%E7%A0%81%E6%A3%80%E6%9F%A5%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97
