### ISSUE TITLE
🐛 [Bug]: Tree组件引入lodash不准确，导致业务方vite构建报错

### ISSUE THREAD

**Issue by xingyan95** [DevCloudFE/vue-devui#373]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/tree/

### Step to reproduce

```ts
//  tree/src/composables/use-draggable.ts

// ... other code

import { cloneDeep } from 'lodash';

// ... other code
```

这一行引用引起 node12/14下，业务方vite构建报错，需要改为 `import cloneDeep from 'lodash/cloneDeep';`

node16版本未出现报错。具体原理目前还不清楚。

**Comment by kagol** [comment]
fixed by @xingyan95 on #374
