### ISSUE TITLE
抽取`click-outside`钩子

### ISSUE THREAD

**Issue by xingyan95** [DevCloudFE/vue-devui#42]
### What problem does this feature solve

针对点击页面空白区域关闭弹出层，目前发现不同组件的实现方式：
- 在`popover`组件中，通过指令`clickoutsideDirective`的方式实现。
- 在`select`组件中，通过钩子`useSelectOutsideClick`的方式实现。

### What does the proposed API look like

建议将此能力提取为钩子，组件间共用。

**Comment by Zcating** [comment]
建议使用 overlay

**Comment by kagol** [comment]
可使用`Overlay`组件或者`vueuse`的`onClickOutside`
