### ISSUE TITLE
🐛 [Bug]: Tree组件不应该从Anchor组件引入工具函数

### ISSUE THREAD

**Issue by xingyan95** [DevCloudFE/vue-devui#422]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/

### Step to reproduce

在`devui/tree/src/core/utils.ts`文件的第一行，从`Anchor`组件中引入了工具函数，应该把通用的工具函数放入`shared`中。

**Comment by kagol** [comment]
赞同，这个工具函数其他组件也会用到，应该放到`shared`目录中

**Comment by kagol** [comment]
fixed by @kagol on #445
