### ISSUE TITLE
文档网站首次渲染白屏

### ISSUE THREAD

**Issue by TinsFox** [DevCloudFE/vue-devui#44]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://github.com/DevCloudFE/vue-devui

### Step to reproduce

按照文档运行项目

### What is expected

首次运行项目打开http://localhost:3000/正常访问，

### What is actually happening

白屏需要刷新才能正常显示

### Any additional comments (optional)

可能是 vite的pre-bundle 的问题

**Comment by GaoNeng-wWw** [comment]
已修复
