### ISSUE TITLE
🐛 [Bug]: 官网readtip组件例子错误

### ISSUE THREAD

**Issue by MICD0704** [DevCloudFE/vue-devui#452]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/read-tip/#%E5%8C%85%E6%8B%AC%E5%A4%9A%E4%B8%AA%E6%8F%90%E7%A4%BA%E7%9A%84readtip

### Step to reproduce

![image](https://user-images.githubusercontent.com/20532893/163309224-22d41b82-043d-474e-a39d-60bee001138e.png)
![image](https://user-images.githubusercontent.com/20532893/163309302-c1cf4efb-78bb-4ac9-9321-63b8171fd29c.png)

### What is expected

官网的示例应该较友好的显示

**Comment by kagol** [comment]
@all-contributors please add @MICD0704 for code and bug
