### ISSUE TITLE
[测试]: Badge组件

### ISSUE THREAD

**Issue by Merlin218** [DevCloudFE/vue-devui#460]
[https://vue-devui.github.io/components/badge](https://vue-devui.github.io/components/badge)

主要测试Badge组件的以下功能：

- [x] 1、count是否正常显示(考虑max-count比较大的情况，显示是否正常)
- [x] 2、max-count逻辑是否正确
- [x] 3、只显示圆点，不显示数字
- [x] 4、五种状态显示是否正常
- [x] 5、四种位置显示是否正常
- [x] 6、背景颜色是否正常设置(bg-color优先级 > status)
- [x] 7、设置文本颜色
- [x] 8、偏移量设置

**Comment by Merlin218** [comment]
@duqingyu 请教一下关于第一点，是否算是正常的显示呢，好像可以加一个`z-index`统一一下？

**Comment by Merlin218** [comment]
find a little bug, #507

**Comment by Merlin218** [comment]
关于第5点：左下角位置显示有偏差
![image-20220417222249119](https://cdn.jsdelivr.net/gh/Merlin218/image-storage/picGo/202204172222163.png)

**Comment by Merlin218** [comment]
[测试demo](https://codesandbox.io/s/strange-jang-u0ws81?file=/src/components/TestBadge.vue)

**Comment by kagol** [comment]
> @duqingyu 请教一下关于第一点，是否算是正常的显示呢，好像可以加一个`z-index`统一一下？ ![image-20220417220858817](https://camo.githubusercontent.com/97aaf3c45563c6f2d099cccc02d49db1e69602a5ca4338cfaf4698dec70edb21/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4d65726c696e3231382f696d6167652d73746f726167652f706963476f2f3230323230343137323230383835382e706e67)

这个长度感觉得限制下，不能这么长，得有个显示规则，最大长度是多少，超出了怎么显示

**Comment by Merlin218** [comment]
嗯嗯，同意此说法。> > @duqingyu 请教一下关于第一点，是否算是正常的显示呢，好像可以加一个`z-index`统一一下？ ![image-20220417220858817](https://camo.githubusercontent.com/97aaf3c45563c6f2d099cccc02d49db1e69602a5ca4338cfaf4698dec70edb21/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4d65726c696e3231382f696d6167652d73746f726167652f706963476f2f3230323230343137323230383835382e706e67)
> 
> 
> 
> 这个长度感觉得限制下，不能这么长，得有个显示规则，最大长度是多少，超出了怎么显示

**Comment by kagol** [comment]
Finished by @Merlin218
