### ISSUE TITLE
[测试]: InputNumber组件

### ISSUE THREAD

**Issue by Merlin218** [DevCloudFE/vue-devui#461]
https://vue-devui.github.io/components/input-number

主要测试 `InputNumber` 组件的以下功能：

- [x] 1、设置步长
- [x] 2、设置 placeholder
- [x] 3、设置最大、最小值
- [x] 4、设置禁用
- [x] 5、设置默认值
- [x] 6、设置尺寸
- [x] 7、change事件
- [x] 8、blur事件
- [x] 9、focus事件
- [x] 10、input事件

**Comment by Merlin218** [comment]
There seems to be a rendering bug #508

**Comment by Merlin218** [comment]
问题：
- 设置步长：max为10，步长为3，最大会增加到12；减小同样存在问题（增加判断逻辑）
- 设置默认值：min为1，值为0，如果用户不修改会导致值不在范[1,10]内（看能否在逐渐挂载之后对值进行判断，然后小于min，自动设置为min）
- input事件：当我们输入一个数字时，浏览器拿到的实际是个字符串，props规定的类型是number，会有warn
优化：
- disabled时的样式与正常没有什么区别，可以加一个样式区分一下
- 尺寸设置，可选属性值`normal`可以改为缩写`md`，另外，`sm`和`normal`的尺寸区分度似乎不是很大，大小差不多。

**Comment by Merlin218** [comment]
@git-Where 以上是我测试的结果，欢迎指正。

**Comment by git-Where** [comment]
针对以上提出的问题以及优化，已做出相应的调整；对于disabled样式没出来，看了你的样例代码是sass没安装，样式变量没生效
。 @Merlin218

**Comment by Merlin218** [comment]
> 针对以上提出的问题以及优化，已做出相应的调整；对于disabled样式没出来，看了你的样例代码是sass没安装，样式变量没生效 。 @Merlin218

👌🏻收到，辛苦了

**Comment by kagol** [comment]
@git-Where @Merlin218 Give a thumbs up to your efficiency and professionalism.👍👍

**Comment by git-Where** [comment]
Can this issue be closed. @kagol
