### ISSUE TITLE
[测试]: Switch组件

### ISSUE THREAD

**Issue by Merlin218** [DevCloudFE/vue-devui#462]
[https://vue-devui.github.io/components/switch/](https://vue-devui.github.io/components/switch/)

主要测试 `Switch` 组件的以下功能：

- [x] 1、设置组件尺寸大小
- [x] 2、设置自定义颜色
- [x] 3、设置选中状态
- [x] 4、设置禁用
- [x] 5、选中时自定义内容(考虑字符较多的情况)
- [x] 6、未选中时自定义内容(同上)
- [x] 7、change事件

**Comment by Merlin218** [comment]
@brenner8023 关于第5、6点，是否可以支持一下插入多字符的内容，目前应该只能插入一个字符，多了会溢出，影响美观。
![image-20220417233203092](https://cdn.jsdelivr.net/gh/Merlin218/image-storage/picGo/202204172332140.png)

**Comment by Merlin218** [comment]
[测试demo](https://codesandbox.io/s/mutable-flower-z691cn?file=/src/components/TestSwitch.vue)

**Comment by kagol** [comment]
Finished by @Merlin218
