### ISSUE TITLE
 [测试]: Tag组件

### ISSUE THREAD

**Issue by ming-bin** [DevCloudFE/vue-devui#463]
https://vue-devui.github.io/components/tag/

主要测试Tag组件的以下功能：

- [x] 设置类型
- [x] 设置主题色
- [x] 设置鼠标悬浮时 title 的显示
- [x] 设置标签选中的初始状态
- [x] 设置标签是否可删除
- [x] 设置deletable属性时是否显示关闭图标
- [x] 点击 tag 的时候触发的事件
- [x] 删除 tag 的时候触发的事件
- [x] tag 的 check 状态改变时触发的事件

**Comment by ming-bin** [comment]
@c0dedance 该组件文档中type参数值与代码中tagType定义的不同

**Comment by c0dedance** [comment]
# tag组件设计

## api设计

### 标签组

+ ng：有

+ vue：不实现其原因是

  标签组完全可以由用户一个for循环控制，不需要再单独建一个组件；且antd/element+均无实现

### 主题色

+ ng
  + labelStyle 预置颜色（blue-w98、或传入自定义 class）
  + customColor 自定义颜色（#eee）
+ vue
  + 新增type
  + 移除labelStyle、customColor ，统一为color。即传blue-w98、#eee均可转为颜色值
  + type color不合并比较好  color=“success” 不是很符合寓意
  + 对比antd，它无type(primary/success..，color传入#eee、red)

### 可移除

+ ng
  + mode.closeable控制
  + deletable控制
+ vue
  + 源码意思好像是2个属性其一都可以控制，感觉冗余，移除了mode这个api；仅由deletable控制

### 标签内容


  + ng：tag传入string 或 customViewTemplate控制

    <img src="https://img.qkeep.cn/imgs/image-20220114232909594.png" alt="image-20220114232909594" style="zoom:50%;"  align="left"/>

  + vue：使用默认插槽，可放置文字图标等


### 可选中的

+ ng
  + mode.checkable、checkable共同控制？
+ vue
  + 感觉冗余，移除了mode此api，仅由checkable控制
  + 对比antd/element+，他们均是抽离出来一个单独的check-tag组件，且不支持自定义颜色；咱的没有抽离，可以设置颜色同时切换是否选中


+ customViewTemplate->默认插槽

### 事件

挺完善的

**Comment by kagol** [comment]
Finished by @ming-bin
