### ISSUE TITLE
[测试]: Rate组件

### ISSUE THREAD

**Issue by ming-bin** [DevCloudFE/vue-devui#465]
https://vue-devui.github.io/components/rate/

主要测试Rate组件的以下功能：

- [x] 设置是否为只读模式
- [x] 设置总等级数
- [x] 设置当前评分的类型
- [x] 设置星星颜色
- [x] 设置评分图标icon
- [x] 设置评分图标的样式character
- [x] 动态模式下是否允许半选
- [x] change事件

**Comment by kagol** [comment]
Finished by @ming-bin
