### ISSUE TITLE
🐛 [Bug]: Slider组件

### ISSUE THREAD

**Issue by Lonely-shang** [DevCloudFE/vue-devui#471]
### Version

1.0.0-rc.5

### Vue Version

3.2.25

### Link to minimal reproduction

https://vue-devui.github.io/components/slider/

### Step to reproduce

` <d-slider
      :min="0"
      :max="100"
      showInput
      disabled
      v-model="inputValue"
    ></d-slider>`

### What is expected

禁止用户输入

### What is actually happening

步进条被禁止了，但是`input`输入框并没被禁止

**Comment by kagol** [comment]
@all-contributors please add @Lonely-shang for test
