### ISSUE TITLE
🐛 [Bug]: seach组件中设置max-length不生效

### ISSUE THREAD

**Issue by Yangxfeng** [DevCloudFE/vue-devui#485]
### Version

vue-devui@1.0.0-rc.5

### Vue Version

vue-devui@1.0.0-rc.5

### Link to minimal reproduction

https://vue-devui.github.io/components/search/

### Step to reproduce

seach组件中设置max-length=”x“后，发现还是可以输入length大于x的数值

### What is expected

预期应该是不可以输入大于max-length的数值

### What is actually happening

![image](https://user-images.githubusercontent.com/35209766/163663003-7dee59a7-6986-47e7-b629-4a15c6131e5a.png)

  <d-search css-class="ipt" v-model="searchText" :max-length="5" style="width: 200px"></d-search>
  
![image](https://user-images.githubusercontent.com/35209766/163663016-33043c41-a3f3-4b53-8a55-8985f6cb98e0.png)

**Comment by kagol** [comment]
Fixed by @zcj996 on #559
