### ISSUE TITLE
🐛 [Bug]: Tag组件文档type类型可选值错误

### ISSUE THREAD

**Issue by ming-bin** [DevCloudFE/vue-devui#486]
### Version

v1.0.0-rc.5

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/tag/#api

### Step to reproduce

文档与代码定义的不一致，文档多了个info类型少了一个primary类型

![微信图片_20220416151914](https://user-images.githubusercontent.com/54826175/163665919-468a1c48-72d8-42ce-a841-f503d79663b0.png)
![微信图片_20220416152015](https://user-images.githubusercontent.com/54826175/163665929-3766fe5e-7301-486c-8c51-c2ccc783711a.png)

**Comment by kagol** [comment]
@all-contributors please add @ming-bin for bug
