### ISSUE TITLE
🐛 [Bug]: Rate组件设置color失效

### ISSUE THREAD

**Issue by ming-bin** [DevCloudFE/vue-devui#488]
### Version

v1.0.0-rc.5

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/rate/#api

### Step to reproduce

`<d-rate v-model="value" color="#ffa500" />`

设置了color但颜色没变化还是默认的颜色

![image](https://user-images.githubusercontent.com/54826175/163667786-d6906a8f-080d-4a72-9383-bd88a6a45dd8.png)

**Comment by Lonely-shang** [comment]
默认图标可以使用type更改颜色， 自定义图标时，`color`属性会生效，不知默认图标不生效是不是故意为之。

**Comment by kagol** [comment]
应该是有问题的，只设置`color`理应生效才对

**Comment by kagol** [comment]
Fixed by @Lonely-shang on #578

**Comment by Lonely-shang** [comment]
这个问题已经修复，你可以关闭它了。（ [#578 ](https://github.com/DevCloudFE/vue-devui/pull/578)）
