### ISSUE TITLE
[测试]: Progress进度条组件

### ISSUE THREAD

**Issue by Lonely-shang** [DevCloudFE/vue-devui#491]
https://vue-devui.github.io/components/progress/

主要测试`Progress`组件以下功能：

- [x] 进度条值
- [x] 进度条当前值文字说明
- [x] 进度条颜色
- [x] 进度条高度
- [x] 设置是否为圈形
- [x] 设置圈形进度条宽度
- [x] 设置圈形进度条内是否展示内容
- [x] 自定义圆环内容

**Comment by kagol** [comment]
Finished by @Lonely-shang
