### ISSUE TITLE
🐛 [Bug]: seach组件，如果没下载图标库的话，搜索按钮会显示空白，无法点击，建议可以设置个默认图标

### ISSUE THREAD

**Issue by Yangxfeng** [DevCloudFE/vue-devui#495]
### Version

vue-devui@1.0.0-rc.5

### Vue Version

vue-devui@1.0.0-rc.5

### Link to minimal reproduction

https://vue-devui.github.io/components/search/

### Step to reproduce

新手使用seach组件，但是如果没下载图标库的话，会没有图标，建议可以设置个默认图标
![image](https://user-images.githubusercontent.com/35209766/163674718-99f548c1-6476-476c-b990-8625a2f2f11f.png)

### What is expected

建议类似的组件可以设置个默认图标

### What is actually happening

实际会直接留白，无法点击搜索，只能通过回车触发search事件

**Comment by zcj996** [comment]
这个不能算bug吧，不引入相关依赖本身是一个错误， 如果设置默认图标，可能会使使用者感到困惑。
当然 不能点击进行搜索，可以算是一个bug。
> 仅代表个人观点

**Comment by kagol** [comment]
这里可能需要进行优化，比如组件库的组件内部不使用字体图标库，而是使用svg，这样使用者即使没有引入字体图标库也不至于显示不了图标
