### ISSUE TITLE
✨ [Feature]: search组件size属性中的""，这个可选类型会让开发者感到费解，而且在某些代码检测插件中可能会被纠错

### ISSUE THREAD

**Issue by Yangxfeng** [DevCloudFE/vue-devui#497]
### What problem does this feature solve

属性为空字符串当作一种类型，从开发设定上来说不太合理，而且在某些代码检测插件下可能会被纠错处理
![image](https://user-images.githubusercontent.com/35209766/163675012-5368af41-6ce7-484f-8fe4-97258c82b0c6.png)

### What does the proposed API look like

可以改成Normal这种语义更明确的字段

**Comment by kagol** [comment]
这里确实有问题，应该改成 'md'

**Comment by kagol** [comment]
@all-contributors please add @Yangxfeng for bug

**Comment by vaebe** [comment]
<img width="675" alt="截屏2022-09-17 下午10 33 49" src="https://user-images.githubusercontent.com/52314078/190862289-0dd59d29-fa99-40bb-a6a2-457973210cd7.png">

问题已不存在
