### ISSUE TITLE
🐛 [Bug]: InputNumber组件

### ISSUE THREAD

**Issue by Merlin218** [DevCloudFE/vue-devui#508]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

[https://codesandbox.io/s/friendly-sinoussi-8m4cvt?file=/src/components/TestInputNumber.vue](https://codesandbox.io/s/friendly-sinoussi-8m4cvt?file=/src/components/TestInputNumber.vue)

### Step to reproduce

- 导入组件
- 使用文档中的代码段

### What is expected

组件正常渲染

### What is actually happening

未出现两个向上增加/向下减少 的箭头

**Comment by Lonely-shang** [comment]
组件的图标需要依赖一个`@devui-design/icons`库 通过`pnpm`安装 引入即可   [#484](https://github.com/DevCloudFE/vue-devui/issues/484)

**Comment by Merlin218** [comment]
> 组件的图标需要依赖一个`@devui-design/icons`库 通过`pnpm`安装 引入即可 [#484](https://github.com/DevCloudFE/vue-devui/issues/484)

ok,thanks.
