### ISSUE TITLE
🐛 [Bug] : 设置fullScreen组件的z-index未生效

### ISSUE THREAD

**Issue by XiaoRIGE** [DevCloudFE/vue-devui#529]
### Version

1.0.0-rc.5

### Vue Version

3.2.25

### Link to minimal reproduction

https://github.com/XiaoRIGE/vue-devui-test

### Step to reproduce

设置了z-index后未生效

**Comment by zcj996** [comment]
![image](https://user-images.githubusercontent.com/52314078/164651277-1b249ed8-5826-47dc-995e-4abd8247eadc.png)
从控制台看 样式是设置了的。

**Comment by XiaoRIGE** [comment]
是我的使用方式不对或者漏了什么地方吗？我使用了这个组件后查看dom是这样的。

以下是源码内容





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DevCloudFE/vue-devui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DevCloudFE/vue-devui] 🐛 [Bug] : 设置fullScreen组件的z-index未生效 (Issue #529)





 

 从控制台看 样式是设置了的。

**Comment by zcj996** [comment]
我模仿你做了下测试，看起来是没有问题的。会不会是版本的问题呢？
![image](https://user-images.githubusercontent.com/52314078/164676741-530208e3-6dab-46e6-86d3-4fb3aae853d2.png)
![image](https://user-images.githubusercontent.com/52314078/164676790-3885368a-ab20-444e-80ba-9b9921d12544.png)

**Comment by XiaoRIGE** [comment]
![image](https://user-images.githubusercontent.com/33147011/164679128-c351f3e3-1ec9-4b6d-93d7-54087bab363b.png)

我尝试更新了vue-devui版本，还是没有对应的样式。
这是我的测试代码地址：https://github.com/XiaoRIGE/vue-devui-test

**Comment by zcj996** [comment]
+ 非常抱歉，我在没有去看你代码的时候就做出判断。
+ `Fullscreen` `mode="immersive"` 沉浸式全屏，应该是不需要设置z-index的全屏的元素会默认在窗口最前边。
> 个人观点

**Comment by XiaoRIGE** [comment]
那我觉得是不是可以在文档的参数说明里 说明一下，如果有必要的话

**Comment by kagol** [comment]
也就是说在普通全屏模式下`z-index`是生效的，但是在全屏模式下`z-index`没有设置到dom元素中对吗？
正常情况下两种模式都应该正常设置`z-index`的。
@XiaoRIGE

**Comment by XiaoRIGE** [comment]
沉浸式全屏模式的时候z-index确实是没有生效的

**Comment by kagol** [comment]
我之前的理解可能是不对的，我又仔细看了下相关的代码，沉浸式全屏调用的是浏览器的api实现的全屏，是跟dom无关的，没必要也不应该加`z-index`，因为浏览器的全屏层级是最高的，不受`z-index`的影响
@XiaoRIGE @zcj996

**Comment by kagol** [comment]
> * 非常抱歉，我在没有去看你代码的时候就做出判断。
> * `Fullscreen` `mode="immersive"` 沉浸式全屏，应该是不需要设置z-index的全屏的元素会默认在窗口最前边。
> 
> > 个人观点

这个理解是正确的。

**Comment by XiaoRIGE** [comment]
确实，是我考虑的不到位 == ，

**Comment by kagol** [comment]
> 确实，是我考虑的不到位 == ，

大家一起讨论下感觉就清晰很多，非常感谢你提的这个issue🤝

**Comment by kagol** [comment]
@all-contributors please add @XiaoRIGE for bug
