### ISSUE TITLE
🎉Vue DevUI 1.0 组件功能测试/单元测试招募

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#532]
Vue DevUI 官网：
[https://vue-devui.github.io/](https://vue-devui.github.io/)

组件测试流程：
1. 在[Issues](https://github.com/DevCloudFE/vue-devui/issues)列表创建一个空白issue，说明你将测试的组件，并在描述中以任务列表的方式列出即将测试的该组件的功能
2. 参照官网文档的[快速开始](https://vue-devui.github.io/quick-start/)，使用`vite`创建一个空的vue3工程：`npm create vite my-vue-app --template vue-ts`
3. 引入 Vue DevUI 组件库及其样式，在`App.vue`中使用该组件
4. 尝试给该组件增加API，测试其功能是否正常
5. 测试发现的任何问题和建议，请在[Issues](https://github.com/DevCloudFE/vue-devui/issues)列表记录
6. 完成贡献，请在此issue下评论完成测试XXX组件的测试，共发现以下问题，并贴出issue链接，管理员会将你加到相应组件的贡献者列表中
7. 期待你成为 DevUI 开源项目的贡献者🎉🎉

> 非常欢迎有能力的开发者提PR顺手修复发现的问题，贡献流程参考：[贡献指南](https://vue-devui.github.io/contributing/)，并补充相应的单元测试，编写单元测试可以参考：[组件单元测试指南](https://github.com/DevCloudFE/vue-devui/wiki/%E7%BB%84%E4%BB%B6%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95%E6%8C%87%E5%8D%97)

Vue DevUI 1.0 包含以下50个组件：

 | 序号 | 组件 |  测试者 | 测试进展 | 修复者 | 修复进展 |
| -- | -- | -- | -- | -- | -- |
| 1 | ✅Button 按钮 | @kagol  |  ✅ |  @vaebe  |  | 
| 2 | ✅Fullscreen 全屏 |    @XiaoRIGE | 2/3 |  |  | 
| 3 | ✅Icon 图标 |    @wzhaofei | ✅ |  |  | 
| 4 | ✅Overlay 遮罩层 |   |  |  |  | 
| 5 | ✅Panel 面板 |  |  |  |   | 
| 6 | ✅Ripple 水波纹 |  |  |  |   | 
| 7 | ✅Search 搜索 |    @Yangxfeng |  |  |  | 
| 8 | ✅Status 状态 |   @XiaoRIGE |  |  |  | 
| 9 | ⭐🚧Dropdown 下拉菜单 |    @Afterain |  |  |  | 
| 10 | ✅Pagination 分页 |    @Afterain and @自然卷  | |  |  | 
| 11 | 🚧Tabs 选项卡 |    @Jae |  |  |  | 
| 12 | ✅Alert 警告 |   @jCodeLife |✅  |  |  | 
| 13 |  🚧Drawer 抽屉板 |  |  |  |   | 
| 14 | ✅Loading 加载提示 |  |  |  |   | 
| 15 | 🚧Modal 弹窗 |   @Ryuuzaki | ✅ |  |  | 
| 16 | ✅Notification 全局通知 |  |  |  |   | 
| 17 | ✅Popover 悬浮提示 |  |  |  |   | 
| 18 | ✅Readtip 阅读提示 |  |  |  |   | 
| 19 | ✅Result 结果 |  |  |  |   | 
| 20 | 🚧Tooltip 提示 |  |  |  |   | 
| 21 | ✅AutoComplete 自动补全 |  |  |  |   | 
| 22 | ✅Checkbox 复选框 |  |  |  |   | 
| 23 | ⭐🚧DatePicker 日期选择器 |  |  |  |   | 
| 24 | ✅EditableSelect 可输入下拉选择框 |  |  |  |   | 
| 25 | ⭐🚧Form 表单 |  |  |  |   | 
| 26 | ✅Input 输入框 |   @c0dedance |  |  |  | 
| 27 | 🚧InputNumber 数字输入框 |     @Merlin218 |  | fixed by @git-Where on #522 |  | 
| 28 | ✅Radio 单选框 |    @c0dedance |  |  |  | 
| 29 | ⭐🚧Select 下拉框 |   @自然卷 |  |  | 
| 30 | ✅Slider 滑块 |   @Lonely-shang | ✅ | fixed by @Lonely-shang on #523 #525  |  | 
| 31 | ✅Switch 开关 |   @Merlin218 | ✅ |  |  | 
| 32 | ✅Textarea 多行文本框 |  |  |  |   | 
| 33 | ✅Upload 上传 |  |  |  |   | 
| 34 | ✅Avatar 头像 |   @ming-bin | ✅ |  |  | 
| 35 | ✅Badge 徽标 |   @Merlin218 |✅  |  |  | 
| 36 | ✅Card 卡片 |   @c0dedance |  |  |  | 
| 37 | ✅Comment 评论 |  |  |  |   | 
| 38 | ✅Countdown 倒计时 | @Lonely-shang | 0/0 |  |   | 
| 39 | ✅ImagePreview 图片预览 |  |  |  |   | 
| 40 | ✅Progress 进度条 |   @Lonely-shang | ✅ |  |  | 
| 41 | ✅Rate 评分 |   @ming-bin and @旅行走失的猫 |  ✅|  |  | 
| 42 | ✅Skeleton 骨架屏 |  |  |  |   | 
| 43 | ✅Statistic 统计数值 |  |  |  |   | 
| 44 | ⭐🚧Table 表格 |   @wzhaofei  | 3/31 |  |  | 
| 45 | ✅Tag 标签 |   @ming-bin, @c0dedance and @旅行走失的猫 |  ✅ |  |  | 
| 46 | ✅Timeline 时间线 |  |  |  |   | 
| 47 | ⭐🚧Tree 树 |  |  |  |   | 
| 48 | ✅Grid 栅格 |  |  |  |   | 
| 49 | ✅Layout 布局 |  |  |  |   | 
| 50 | ✅Splitter 分割器 |  @jingyiliu |  |  |  |

**Comment by jCodeLife** [comment]
完成 Alert 组件的测试，10 tasks 未发现问题 [#547](https://github.com/DevCloudFE/vue-devui/issues/547)

**Comment by kagol** [comment]
2022.4.26 更新：
目前Button组件全部功能都测试完成，发现以下问题：
- [ ] #484
- [x] #558 Fixed by @zcj996 on #567 
- [ ] #568 
- [ ] #571 
- [ ] #573 
- [ ] #575 
- [ ] #576
