### ISSUE TITLE
【测试】Alert 组件

### ISSUE THREAD

**Issue by jCodeLife** [DevCloudFE/vue-devui#547]
https://vue-devui.github.io/components/alert/

主要测试 Alert 组件的以下功能：
  

- [x] 设置警告的类型 type 
- [x] 查看警告的默认类型
- [x] 设置警告的可关闭 closeable
- [x] 检测 closeable 的默认是否为 true
- [x] 设置使用类型图标 show-icon
- [x] 检测 show-icon 的默认值是否为 true
- [x] 设置自定义 class 名 css-class
- [x] 设置自动关闭 alert 的延迟时间 dismiss-time
- [x] 设置关闭时触发的回调函数 close
- [x] 检测当使用 dismiss-time 时关闭警告时，close 是否生效
- [x] 当警告中的字体变大时，样式变化

**Comment by jCodeLife** [comment]
最后一条，当字体变化时，右边的关闭按钮位置异常，如图 👇

![1650508764(1)](https://user-images.githubusercontent.com/50767049/164360910-19d95f9f-8c69-4c48-a021-9a6122ceb62c.jpg)

**Comment by kagol** [comment]
Finished by @jCodeLife
