### ISSUE TITLE
[测试]: Modal组件

### ISSUE THREAD

**Issue by eru-Ryuuzaki** [DevCloudFE/vue-devui#549]
https://vue-devui.github.io/components/modal/
主要测试Modal组件以下功能：
- [x] 是否正常显示浮层
- [x]  测试自定义标题和显示按钮(自定义标题 header 插槽优先级高于 title )
- [x] 测试关闭前回调
- [x] 测试服务方式调用
- [x] 测试是否能将 body 滚动锁定
- [x] 测试点击遮罩层是否能关闭 Modal

**Comment by kagol** [comment]
Finished by @eru-Ryuuzaki
