### ISSUE TITLE
🐛 [Bug]: AutoComplete组件使用Tab键聚焦之后，输入"J"之后，又被自动删除了

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#557]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

创建一个vite工程，按照以下方式使用：
```vue
<script setup lang="ts">
import { ref } from 'vue'

const source = ref([
  'C#',
  'C',
  'C++',
  'CPython',
  'Java',
  'JavaScript',
  'Go',
  'Python',
  'Ruby',
  'F#',
  'TypeScript',
  'SQL',
  'LiveScript',
  'CoffeeScript',
]);
</script>

<template>
  <d-auto-complete :source="source"></d-auto-complete>
</template>
```

### Step to reproduce

使用Tab键聚焦AutoComplete组件，然后输入"J"，自动完成下拉框弹出来了，但是输入框中的"J"被自动删除了。
![image](https://user-images.githubusercontent.com/9566362/164455785-eea3e7ad-e56a-4a0f-90f9-be9cbce1ab87.png)

### What is expected

期望"J"不被删除

### What is actually happening

实际上"J"被删除

### Any additional comments (optional)

直接点击输入框输入"J"没有问题

**Comment by zxlfly** [comment]
这个问题是因为没有使用v-model绑定数据的原因，默认值为''，一般使用这个组件是需要这个值

**Comment by kagol** [comment]
> 这个问题是因为没有使用v-model绑定数据的原因，默认值为''，一般使用这个组件是需要这个值

我刚试了下加上 v-model 确实可以了，我先关闭这个 issue
