### ISSUE TITLE
🐛 [Bug]: Grid组件组件黑暗主题下背景颜色错误

### ISSUE THREAD

**Issue by GaoNeng-wWw** [DevCloudFE/vue-devui#563]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

[Grid](https://vue-devui.github.io/components/grid/)

### Step to reproduce

访问文档，切换至任意一个黑暗主题
![M~`6$~0KG06_U9KY{TYBXSR](https://user-images.githubusercontent.com/31283122/164886271-f5287262-c8b2-4adb-8e6f-a4281f089fc8.png)

### What is expected

应该随背景颜色改变而改变

### What is actually happening

也许是没有增加background或background颜色不对

### Any additional comments (optional)

/

**Comment by liyao1520** [comment]
认领
是因为组件文档demo把css颜色写死了,改为css var() 即可

**Comment by kagol** [comment]
Fixed by @liyao1520 on #825
