### ISSUE TITLE
文档中 Tag 背景色

### ISSUE THREAD

**Issue by whylost** [DevCloudFE/vue-devui#582]
**如下图, 这是刻意为之的吗, 让人感觉 tag组件 必带背景色一样**
是不是在文档中应该少加一些修饰 呈现组件的原样
![image](https://user-images.githubusercontent.com/62528887/165271742-79b0e0a5-b024-44ca-be24-e337867ea21b.png)
![image](https://user-images.githubusercontent.com/62528887/165271829-0aadc899-34d8-404b-a843-a497bfbf6650.png)

**Comment by zcj996** [comment]
这个应该是个bug。
