### ISSUE TITLE
无法正常启动项目

### ISSUE THREAD

**Issue by allenli178** [DevCloudFE/vue-devui#583]
按照文档来操作，但是在运行 `pnpm dev` 时，无法运行
![image](https://user-images.githubusercontent.com/53218750/165310815-01c38555-7ab0-469f-a34e-7214c76050a4.png)

**Comment by allenli178** [comment]
如果我执行 `pnpm dev` ,就会递归调用 dev 脚本
![image](https://user-images.githubusercontent.com/53218750/165317063-a0a4e754-80be-4cb0-8890-b92fa92d8aca.png)
![image](https://user-images.githubusercontent.com/53218750/165317169-8616db76-76e5-491d-aa59-1bdafd367ddf.png)

**Comment by allenli178** [comment]
![image](https://user-images.githubusercontent.com/53218750/165321011-cd62a8f8-8cfd-4290-8868-dab5d74e6929.png)
按文档中来无法执行  打开网站要到packages/devui-vue目录下启动vitepress

**Comment by zcj996** [comment]
可以尝试把pnpm版本换成 6.x，没有发现这个问题。

**Comment by allenli178** [comment]
离谱。pnpm 6.x可以用  7.x不行  这算不算是个bug

**Comment by zcj996** [comment]
从上边截图看 pnpm7.x 并不是稳定版本。
所以这个问题，可能还需要观察。
> 个人意见
