### ISSUE TITLE
🐛 [Bug]: Grid组件文档问题

### ISSUE THREAD

**Issue by xingyan95** [DevCloudFE/vue-devui#63]
### Version

v1.0.0-beta.12

### Vue Version

3.1.1

### Link to minimal reproduction

https://vue-devui.github.io/components/grid/

### Step to reproduce

【对齐】demo中，文案与实际展示的效果不符。
![image](https://user-images.githubusercontent.com/11143986/147196583-8d4737b0-8772-42f4-8c7f-d57866e2abde.png)

### What is expected

文案应修改为：`Justify start`。

**Comment by kagol** [comment]
fixed by @ming-bin on #123
