### ISSUE TITLE
🐛 [Bug]: editable-select组件选择数据之后再次点击会出现层叠问题

### ISSUE THREAD

**Issue by Lonely-shang** [DevCloudFE/vue-devui#655]
### Version

 latest

### Vue Version

3.2.25

### Link to minimal reproduction

https://vue-devui.github.io/components/editable-select/

### Step to reproduce

选择一条数据后 再次点击输入框， 出现的下拉框会出现重复的边框
<img width="605" alt="image" src="https://user-images.githubusercontent.com/34124930/167291114-86449896-adb4-416d-8fd0-f15286ff30ca.png">

### What is expected

不应出现层叠效果

### What is actually happening

<img width="605" alt="image" src="https://user-images.githubusercontent.com/34124930/167291151-9d4ccbeb-950d-493b-845e-70003230d477.png">

**Comment by chenxi24** [comment]
> ### Version
> latest
> 
> ### Vue Version
> 3.2.25
> 
> ### Link to minimal reproduction
> https://vue-devui.github.io/components/editable-select/
> 
> ### Step to reproduce
> 选择一条数据后 再次点击输入框， 出现的下拉框会出现重复的边框 <img alt="image" width="605" src="https://user-images.githubusercontent.com/34124930/167291114-86449896-adb4-416d-8fd0-f15286ff30ca.png">
> 
> ### What is expected
> 不应出现层叠效果
> 
> ### What is actually happening
> <img alt="image" width="605" src="https://user-images.githubusercontent.com/34124930/167291151-9d4ccbeb-950d-493b-845e-70003230d477.png">
> 
> ### Any additional comments (optional)
> _No response_

我试了一下并没有出现这种情况，能否提供详细的复现步骤。

**Comment by kagol** [comment]
我看已经解决了～
