### ISSUE TITLE
✨ [Feature]: 【d-auto-complete】支持clearable属性、clear事件

### ISSUE THREAD

**Issue by newer2333** [DevCloudFE/vue-devui#673]
### What problem does this feature solve

【d-auto-complete】支持clearable属性和clear事件

### What does the proposed API look like

1、支持属性：clearable，可以一键清空输入框内容

![image](https://user-images.githubusercontent.com/32949033/168221894-d5fcf8e0-728b-488c-9853-5864836f9115.png)

2、支持clear事件，在点击由 clearable 属性生成的清空按钮时触发
<d-auto-complete
    v-model="input1"
    placeholder="Pick a date"
    clearable
    @clear="clearData"
/>

**Comment by kagol** [comment]
具体样式需要遵循devui设计规范，可参考Search组件：
[https://devui.design/components/zh-cn/search/](https://devui.design/components/zh-cn/search/)

**Comment by newer2333** [comment]
我计划开始着手开发d-input的clearable属性、clear事件，功能相同，这个issue因此关闭
