### ISSUE TITLE
Avatar组件`gender`属性传入错误值会引起vue警告

### ISSUE THREAD

**Issue by Lonely-shang** [DevCloudFE/vue-devui#689]
当`gender`属性传入错误值vue会报一个警告，`[Vue warn]: Unhandled error during execution of setup function `
我不太清楚，这算不算一个错误。因为这里抛出了个异常。
```javascript
  const getBackgroundColor = (char: string): void => {
      if (gender.value) {
        if (gender.value.toLowerCase() === 'male') {
          code.value = 1;
        } else if (gender.value.toLowerCase() === 'female') {
          code.value = 0;
        } else {
          throw new Error('gender must be "Male" or "Female"');
        }
        return;
      }
      const unicode = char.charCodeAt(0);
      code.value = unicode % 2;
  };
```

**Comment by kagol** [comment]
这种我觉得是不是组件里面给个warning就够了，没必要`throw new Error`，这个`throw new Error`会让人感觉是一个很严重的错误

**Comment by Lonely-shang** [comment]
> @Lonely-shang 这种我觉得是不是组件里面给个warning就够了，没必要`throw new Error`，这个`throw new Error`会让人感觉是一个很严重的错误。另外导致vue warn肯定是不对的，不知道这个vue warn是不是跟这个`throw new Error`有关。

我也这样认为， 当使用者传错或者不传，他在生产环境就能及时发现

**Comment by kagol** [comment]
Fixed by @Lonely-shang on #716
