### ISSUE TITLE
`Comment` 组件 `actions` 属性问题

### ISSUE THREAD

**Issue by Lonely-shang** [DevCloudFE/vue-devui#728]
这是我在修改测试时遇到的一个问题。
文档说明解释 `actions` 属性是一个  操作按钮 类型是一个数组， 但并不能传入一个按钮组件的一个数组。

 传入字符串时不能再一行显示， 这个是否是正常的设计。
```vue
<d-comment
    avatar=""
    author="郑迪"
    datetime="10小时前"
    :actions="['1', '2']"
  >
   用于对事物的讨论，例如页面、博客文章、问题等等。
</d-comment>
```
<img width="786" alt="image" src="https://user-images.githubusercontent.com/34124930/169686744-5d32f4ec-e700-4b9b-85ac-b1b12a093b9b.png">

如果这个属性不能传入一个按钮组件的数组。那么是不是这个属性的介绍容易让人产生误解，还是有其他的方法

**Comment by kagol** [comment]
目前actions属性确实存在问题，可以先把actions属性去掉，先使用actions插槽方式使用，后续再看下怎么支持
