### ISSUE TITLE
✨ [Feature]: Tree组件支持搜索过滤

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/vue-devui#775]
### What problem does this feature solve

支持搜索高亮相应的节点，过滤则会隐藏相应的节点。

![image](https://user-images.githubusercontent.com/9566362/170664013-f79db196-3f1d-4a3c-b931-3330d015282b.png)

### What does the proposed API look like

参考 Ng DevUI [搜索过滤](https://devui.design/components/zh-cn/tree/demo#search-filtering)

**Comment by daviForevel** [comment]
已完成
