### ISSUE TITLE
🐛 [Bug]: Search 搜索框组件和Tab选项卡组件的关闭或清除按钮点击无效，只有点击icon旁边的按钮区域才生效

### ISSUE THREAD

**Issue by diyializhen** [DevCloudFE/vue-devui#917]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/search/
https://vue-devui.github.io/components/tabs/#%E6%B7%BB%E5%8A%A0-%E5%88%A0%E9%99%A4

### Step to reproduce

官网的组件示例点一下就可以发现了

### What is expected

应该触发事件的icon不应该阻止冒泡

### What is actually happening

可能是icon阻止了事件冒泡？正常情况操作组件都是点击按钮中心位置，点击无反应用户肯定觉得是bug。
可能不止这两个组件？

**Comment by vaebe** [comment]
这个已经修复了 @kagol   搜索框的点击 和tabs的清除文档是正常的。
