### ISSUE TITLE
🐛 [Bug]: Modal弹框关闭按钮样式有问题

### ISSUE THREAD

**Issue by diyializhen** [DevCloudFE/vue-devui#918]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/modal/

### Step to reproduce

![bug](https://user-images.githubusercontent.com/25969443/175853423-195785cc-5722-49aa-8b1c-3d77358211d4.jpg)

**Comment by Husky-Yellow** [comment]
这个 我想试试修复一下

**Comment by kagol** [comment]
Fixed by @Husky-Yellow on #928
