### ISSUE TITLE
✨ [Feature]: popover组件未实现controlled属性

### ISSUE THREAD

**Issue by AlanLee97** [DevCloudFE/vue-devui#97]
### What problem does this feature solve

# 问题描述
Form组件中使用了popover组件，其中遇到一个问题是校验时机为change的情况下，popover显示之后又关闭了的情况。

我这边排查到的原因是popover组件使用了clickoutside指令，导致先显示了popover组件，然后点击popover组件之外的区域，把popover组件给关闭了。
![image](https://user-images.githubusercontent.com/42601044/147384314-4f38662d-dfdc-4529-99cc-e0738555a14e.png)

# 解决点
- Popover应实现controlled属性
controlled属性，用于手动控制popover显示方式（[ng版有该API](https://devui.design/components/zh-cn/popover/api#dPopover)）
![image](https://user-images.githubusercontent.com/42601044/147384362-54f977d1-64d7-4e48-9d98-a226cc2d970e.png)
Popover组件实现controlled属性之后，Form组件中可以手动控制popover是否需要点击外部区域关闭popover 

### What does the proposed API look like

# 期望API
- 增加controlled属性
- 通过controlled属性控制是否执行clickoutside指令，实现手动控制是否关闭popover组件

**Comment by CatsAndMice** [comment]
好的同学

**Comment by CatsAndMice** [comment]
周末我修改下

**Comment by CatsAndMice** [comment]
@AlanLee97 该属性已合并   你看下是否满足你的功能

**Comment by AlanLee97** [comment]
> 

好的 我有空验证下 @CatsAndMice

**Comment by AlanLee97** [comment]
可以手动控制显示了，但是有个小问题
- watch的visible的改变时不应该被controlled属性拦截掉
![image](https://user-images.githubusercontent.com/42601044/147438270-c498b339-84c8-419c-9f15-ea36cf822181.png)

**Comment by CatsAndMice** [comment]
@AlanLee97  这个issue可以关掉了
