### ISSUE TITLE
🐛 [Bug]: 组件页面 切换下一个 出现问题

### ISSUE THREAD

**Issue by linxiang07** [DevCloudFE/vue-devui#973]
### Version

v1.0.0-rc.11

### Vue Version

3.2.29

### Link to minimal reproduction

![image](https://user-images.githubusercontent.com/40119767/177073656-8c0e89dd-86ee-49b7-b62b-d0748e49f042.png)

### Step to reproduce

打开[主页](https://vue-devui.github.io/components/countdown/#countdown-%E6%8F%92%E6%A7%BD)

### Any additional comments (optional)

按照道理来说甘特图组件被屏蔽了，可是 countdown 下一个还是甘特图组件，正常应该是ImagePreview组件

[https://vue-devui.github.io/components/countdown/#countdown-%E6%8F%92%E6%A7%BD](url)

**Comment by kagol** [comment]
确实存在这个问题
