### ISSUE TITLE
🐛 [Bug]: HTML button样式reset不彻底问题，ImagePreview复现

### ISSUE THREAD

**Issue by ZhangTaibin** [DevCloudFE/vue-devui#993]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

Windows Microsoft Edge:
![image](https://user-images.githubusercontent.com/34602394/177300718-80ef6d74-4289-4270-a41d-b11117b17521.png)

Windows Firefox:
![image](https://user-images.githubusercontent.com/34602394/177300818-8197e45e-21b5-468e-98fa-afb5cb53d7f0.png)

### Step to reproduce

官方文档就可以复现：
https://vue-devui.github.io/components/image-preview/

### Any additional comments (optional)

组件库部分HTML自带的控件清除样式不彻底，导致Windows上的显示效果明显跟贵项目的预期有所差距。目前发现了button控件的问题，可能还存在别的。

**Comment by kagol** [comment]
确实存在这个问题
