### ISSUE TITLE
🐛 [Bug]: Search搜索框，按钮区域（清除按钮/搜索按钮）点击后输入框会失去焦点

### ISSUE THREAD

**Issue by xzxldl55** [DevCloudFE/vue-devui#997]
### Version

latest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/search/
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/22699218/177474546-6c3598e4-7731-45f0-bdf3-0ba78cb97bd7.png">

### Step to reproduce

可在文档直接复现

### What is expected

点击按钮后，焦点依旧在输入框。
如点击清空按钮x后，焦点仍然在输入框内，可以直接进行输入

### What is actually happening

按钮区域（清除按钮/搜索按钮）点击后输入框会失去焦点

**Comment by kagol** [comment]
Fixed by @xzxldl55 on #1002
