### ISSUE TITLE
🐛 [Bug]: Icon组件的样式问题

### ISSUE THREAD

**Issue by xGuangsPBD** [DevCloudFE/vue-devui#998]
### Version

lastest

### Vue Version

latest

### Link to minimal reproduction

https://vue-devui.github.io/components/steps/

### Step to reproduce

点击下一步

### What is expected

finished状态下的dot-container表现应该和其他状态一致

### What is actually happening

finished状态下的dot-container高度比其他状态高，导致描述文字的位置偏下

### Any additional comments (optional)

由此发现Icon组件的devui-icon__container有着display:inline-flex样式，该样式会使其子元素的vertical-align属性失效。

**Comment by kagol** [comment]
确实有这个问题
